In [1]:
import pandas as pd
import geopandas as gpd
import altair as alt
import json
from shapely.geometry import shape
from shapely import wkt

https://developer.tmb.cat/data

# Metro Stops

In [2]:
with open('data/metro_stops.json') as f:
    data = json.load(f)

2.17623558, 41.3760069

In [3]:
stops = ['Catalunya','Liceu','Drassanes','Paral·lel','Poble Sec','Tarragona','Espanya','Plaça del Centre','Sants Estació','Les Corts','Maria Cristina','Palau Reial']

In [4]:
df = []
for stop in data['features']:
    properties = stop.get('properties', {})
    nom_estacio = properties.get('NOM_ESTACIO')
    
    if nom_estacio in stops:
        df.append({
            'name': nom_estacio,
            'stop_type': 'Metro',
            'geometry': shape(stop['geometry'])
        })

In [5]:
point1 = shape({
    'type': 'Point',
    'coordinates': (2.167342560951652, 41.38704037682107)
})

point2 = shape({
    'type': 'Point',
    'coordinates': (2.1768302000749906, 41.39610145325573)
})

point3 = shape({
    'type': 'Point',
    'coordinates': (2.1130282510923517, 41.38913433225749)
})

point4 = shape({
    'type': 'Point',
    'coordinates': (2.114055470466503, 41.38275273204058)
})

point5 = shape({
    'type': 'Point',
    'coordinates': (2.113665627357394, 41.384072542881135)
})

point6 = shape({
    'type': 'Point',
    'coordinates': (2.1156528732436075, 41.38484302209972)
})


point7 = shape({
    'type': 'Point',
    'coordinates': (2.114321704292043, 41.38591311049023)
})

point8 = shape({
    'type': 'Point',
    'coordinates': (2.1206922984531587, 41.38747540788272)
})






df.append({
    'name': 'Ronda Universitat',
    'stop_type': 'Bus',
    'geometry': point1
})

df.append({
    'name': 'Plaça Tetuan',
    'stop_type': 'Bus',
    'geometry': point2
})


df.append({
    'name': 'Fib',
    'stop_type': 'University',
    'geometry': point3
})

df.append({
    'name': 'Belles Arts',
    'stop_type': 'University',
    'geometry': point4
})

df.append({
    'name': 'Arquitectura',
    'stop_type': 'University',
    'geometry': point5
})

df.append({
    'name': 'FME',
    'stop_type': 'University',
    'geometry': point6
})

df.append({
    'name': 'Economia i Empresa',
    'stop_type': 'University',
    'geometry': point7
})

df.append({
    'name': 'Dret',
    'stop_type': 'University',
    'geometry': point8
})


geo_df_stops = gpd.GeoDataFrame(df)

# Metro Trajectories

In [6]:
with open('data/metro_trajectories.json') as f:
    trajectories = json.load(f)

In [7]:
trajectories

{'type': 'FeatureCollection',
 'features': [{'type': 'Feature',
   'id': 'TRAMS_LINIA.fid--7b6bcf9f_19e019dfb23_17d1',
   'geometry': {'type': 'MultiLineString',
    'coordinates': [[[2.09846443, 41.34213332],
      [2.09894434, 41.3420114],
      [2.10047039, 41.34162018],
      [2.100786, 41.34154995],
      [2.10107923, 41.34149862],
      [2.10120748, 41.34148532],
      [2.10137053, 41.34147109],
      [2.10156665, 41.34146786],
      [2.10175943, 41.34147652],
      [2.10201047, 41.3415035],
      [2.1022644, 41.34154957],
      [2.10245186, 41.34159989],
      [2.10269111, 41.3416804],
      [2.10292525, 41.34178589],
      [2.10312692, 41.34189459],
      [2.10357745, 41.34218586],
      [2.10724192, 41.34467731]]]},
   'geometry_name': 'GEOMETRY',
   'properties': {'CODI_TRAM_LINIA': '0.111',
    'CODI_ESTACIO_INI': 0,
    'NOM_ESTACIO_INI': 'Inici',
    'CODI_ESTACIO_FI': 111,
    'NOM_ESTACIO_FI': 'Hospital de Bellvitge',
    'NOM_TRAM_LINIA': 'Inici - Hospital de Bellvitge',
    'ID_LINIA': 4,
    'CODI_LINIA': 1,
    'NOM_LINIA': 'L1',
    'ORDRE_LINIA': 1,
    'ORIGEN_SERVEI': 'Hospital de Bellvitge',
    'DESTI_SERVEI': 'Fondo',
    'DESC_SERVEI': 'Hospital de Bellvitge - Fondo',
    'ORDRE_TRAM': 1,
    'DATA': '2026-05-06Z',
    'COLOR_LINIA': 'CE1126',
    'ORIENTACIO_TEXT': 1,
    'LONGITUD': 874.928}},
  {'type': 'Feature',
   'id': 'TRAMS_LINIA.fid--7b6bcf9f_19e019dfb23_17d2',
   'geometry': {'type': 'MultiLineString',
    'coordinates': [[[2.10724192, 41.34467731],
      [2.10773411, 41.34501207],
      [2.10809745, 41.34527093],
      [2.10844735, 41.3455401],
      [2.10870319, 41.34575063],
      [2.10891938, 41.34593358],
      [2.10926624, 41.3462134],
      [2.10962699, 41.34648309],
      [2.11000111, 41.34674222],
      [2.11120807, 41.34753837],
      [2.11126628, 41.34757941],
      [2.11133019, 41.3476276],
      [2.11145633, 41.34773035],
      [2.11158898, 41.34785836],
      [2.11170587, 41.34799482],
      [2.11180606, 41.34813862],
      [2.11188873, 41.34828862],
      [2.11195324, 41.3484436],
      [2.11199905, 41.34860231],
      [2.1120258, 41.34876347],
      [2.11203326, 41.34892579],
      [2.11202139, 41.34908796],
      [2.11199027, 41.34924869],
      [2.11194017, 41.34940665],
      [2.11187146, 41.3495606],
      [2.11179386, 41.34969964],
      [2.11177615, 41.34972788],
      [2.1114426, 41.35021522],
      [2.110917, 41.35097554]]]},
   'geometry_name': 'GEOMETRY',
   'properties': {'CODI_TRAM_LINIA': '111.112',
    'CODI_ESTACIO_INI': 111,
    'NOM_ESTACIO_INI': 'Hospital de Bellvitge',
    'CODI_ESTACIO_FI': 112,
    'NOM_ESTACIO_FI': 'Bellvitge',
    'NOM_TRAM_LINIA': 'Hospital de Bellvitge - Bellvitge',
    'ID_LINIA': 4,
    'CODI_LINIA': 1,
    'NOM_LINIA': 'L1',
    'ORDRE_LINIA': 1,
    'ORIGEN_SERVEI': 'Hospital de Bellvitge',
    'DESTI_SERVEI': 'Fondo',
    'DESC_SERVEI': 'Hospital de Bellvitge - Fondo',
    'ORDRE_TRAM': 2,
    'DATA': '2026-05-06Z',
    'COLOR_LINIA': 'CE1126',
    'ORIENTACIO_TEXT': 1,
    'LONGITUD': 882.209}},
  {'type': 'Feature',
   'id': 'TRAMS_LINIA.fid--7b6bcf9f_19e019dfb23_17d3',
   'geometry': {'type': 'MultiLineString',
    'coordinates': [[[2.110917, 41.35097554],
      [2.11052226, 41.35154431],
      [2.11044319, 41.35164954],
      [2.11036385, 41.35174096],
      [2.11029089, 41.35181744],
      [2.11015311, 41.35194241],
      [2.11000082, 41.35205742],
      [2.10983528, 41.35216152],
      [2.10971237, 41.35222737],
      [2.10965773, 41.35225453],
      [2.10947246, 41.35233601],
      [2.10740377, 41.35310457],
      [2.10702679, 41.35325088],
      [2.10679973, 41.35334706],
      [2.10665043, 41.35341733],
      [2.10640122, 41.35354816],
      [2.10616354, 41.35369063],
      [2.10593831, 41.35384417],
      [2.10572646, 41.35400816],
      [2.10552884, 41.35418195],
      [2.10534624, 41.35436483],
      [2.10521856, 41.35450876],
      [2.10518605, 41.3545488],
      [2.10498102, 41.3548172],
      [2.10394401, 41.35630114],
      [2.10344566, 41.35701164],
      [2.10339102, 41.35708643],
      [2.10321933, 41.35734104],
      [2.10306512, 41.35760192],
      [2.10292879, 41.3578684],
      [2.10263153, 41.35855331]]]},
   'geometry_name': 'GEOMETRY',
   'properties': {'CODI_TRAM_LINIA': '112.113',
    'CODI_ESTACIO_INI': 112,
    'NOM_ESTACIO_INI': 'Bellvitge',
    'CODI_ESTACIO_FI': 113,
    'NOM_ESTACIO_FI': 'Av. Carrilet',
    'NOM_TRAM_LINIA': 'Bellvitge - Av. Carrilet',
    'ID_LINIA': 4,
    'CODI_LINIA': 1,
    'NOM_LINIA': 'L1',
    'ORDRE_LINIA': 1,
    'ORIGEN_SERVEI': 'Hospital de Bellvitge',
    'DESTI_SERVEI': 'Fondo',
    'DESC_SERVEI': 'Hospital de Bellvitge - Fondo',
    'ORDRE_TRAM': 3,
    'DATA': '2026-05-06Z',
    'COLOR_LINIA': 'CE1126',
    'ORIENTACIO_TEXT': -2,
    'LONGITUD': 1133.654}},
  {'type': 'Feature',
   'id': 'TRAMS_LINIA.fid--7b6bcf9f_19e019dfb23_17d4',
   'geometry': {'type': 'MultiLineString',
    'coordinates': [[[2.10263153, 41.35855331],
      [2.10201605, 41.359965],
      [2.10185112, 41.36030031],
      [2.10166828, 41.3606303],
      [2.10016742, 41.36322379],
      [2.10010176, 41.36334046],
      [2.09995592, 41.36362595],
      [2.09989051, 41.36376897],
      [2.09974934, 41.36408991]]]},
   'geometry_name': 'GEOMETRY',
   'properties': {'CODI_TRAM_LINIA': '113.114',
    'CODI_ESTACIO_INI': 113,
    'NOM_ESTACIO_INI': 'Av. Carrilet',
    'CODI_ESTACIO_FI': 114,
    'NOM_ESTACIO_FI': 'Rambla Just Oliveras',
    'NOM_TRAM_LINIA': 'Av. Carrilet - Rambla Just Oliveras',
    'ID_LINIA': 4,
    'CODI_LINIA': 1,
    'NOM_LINIA': 'L1',
    'ORDRE_LINIA': 1,
    'ORIGEN_SERVEI': 'Hospital de Bellvitge',
    'DESTI_SERVEI': 'Fondo',
    'DESC_SERVEI': 'Hospital de Bellvitge - Fondo',
    'ORDRE_TRAM': 4,
    'DATA': '2026-05-06Z',
    'COLOR_LINIA': 'CE1126',
    'ORIENTACIO_TEXT': -2,
    'LONGITUD': 660.855}},
  {'type': 'Feature',
   'id': 'TRAMS_LINIA.fid--7b6bcf9f_19e019dfb23_17d5',
   'geometry': {'type': 'MultiLineString',
    'coordinates': [[[2.09974934, 41.36408991],
      [2.09946258, 41.36474177],
      [2.09941978, 41.36484881],
      [2.09938219, 41.36496697],
      [2.09936009, 41.36504998],
      [2.09932887, 41.36521962],
      [2.09931687, 41.36539063],
      [2.09932416, 41.3655618],
      [2.09935069, 41.36573189],
      [2.09939628, 41.36589967],
      [2.09946059, 41.36606393],
      [2.09954315, 41.36622348],
      [2.09964338, 41.3663772],
      [2.09976055, 41.36652394],
      [2.09989383, 41.36666268],
      [2.10004224, 41.36679241],
      [2.10020472, 41.36691218],
      [2.1003801, 41.36702115],
      [2.10056711, 41.36711851],
      [2.10076441, 41.36720358],
      [2.10093425, 41.36726417],
      [2.10102822, 41.36729446],
      [2.10124365, 41.36735369],
      [2.10275752, 41.36769401]]]},
   'geometry_name': 'GEOMETRY',
   'properties': {'CODI_TRAM_LINIA': '114.115',
    'CODI_ESTACIO_INI': 114,
    'NOM_ESTACIO_INI': 'Rambla Just Oliveras',
    'CODI_ESTACIO_FI': 115,
    'NOM_ESTACIO_FI': 'Can Serra',
    'NOM_TRAM_LINIA': 'Rambla Just Oliveras - Can Serra',
    'ID_LINIA': 4,
    'CODI_LINIA': 1,
    'NOM_LINIA': 'L1',
    'ORDRE_LINIA': 1,
    'ORIGEN_SERVEI': 'Hospital de Bellvitge',
    'DESTI_SERVEI': 'Fondo',
    'DESC_SERVEI': 'Hospital de Bellvitge - Fondo',
    'ORDRE_TRAM': 5,
    'DATA': '2026-05-06Z',
    'COLOR_LINIA': 'CE1126',
    'ORIENTACIO_TEXT': 1,
    'LONGITUD': 572.329}},
  {'type': 'Feature',
   'id': 'TRAMS_LINIA.fid--7b6bcf9f_19e019dfb23_17d6',
   'geometry': {'type': 'MultiLineString',
    'coordinates': [[[2.10275752, 41.36769401],
      [2.10381341, 41.36793039],
      [2.10477541, 41.36814377],
      [2.10506957, 41.36819996],
      [2.10516005, 41.3682143],
      [2.10526194, 41.36822881],
      [2.10552523, 41.36825609],
      [2.10559149, 41.36826089],
      [2.10589445, 41.36827412],
      [2.10597151, 41.36827517],
      [2.10873813, 41.36829612],
      [2.10915936, 41.36830119],
      [2.11002737, 41.36831605]]]},
   'geometry_name': 'GEOMETRY',
   'properties': {'CODI_TRAM_LINIA': '115.116',
    'CODI_ESTACIO_INI': 115,
    'NOM_ESTACIO_INI': 'Can Serra',
    'CODI_ESTACIO_FI': 116,
    'NOM_ESTACIO_FI': 'Florida',
    'NOM_TRAM_LINIA': 'Can Serra - Florida',
    'ID_LINIA': 4,
    'CODI_LINIA': 1,
    'NOM_LINIA': 'L1',
    'ORDRE_LINIA': 1,
    'ORIGEN_SERVEI': 'Hospital de Bellvitge',
    'DESTI_SERVEI': 'Fondo',
    'DESC_SERVEI': 'Hospital de Bellvitge - Fondo',
    'ORDRE_TRAM': 6,
    'DATA': '2026-05-06Z',
    'COLOR_LINIA': 'CE1126',
    'ORIENTACIO_TEXT': 1,
    'LONGITUD': 616.67}},
  {'type': 'Feature',
   'id': 'TRAMS_LINIA.fid--7b6bcf9f_19e019dfb23_17d7',
   'geometry': {'type': 'MultiLineString',
    'coordinates': [[[2.11002737, 41.36831605],
      [2.11117155, 41.36833438],
      [2.11659379, 41.36839566]]]},
   'geometry_name': 'GEOMETRY',
   'properties': {'CODI_TRAM_LINIA': '116.117',
    'CODI_ESTACIO_INI': 116,
    'NOM_ESTACIO_INI': 'Florida',
    'CODI_ESTACIO_FI': 117,
    'NOM_ESTACIO_FI': 'Torrassa',
    'NOM_TRAM_LINIA': 'Florida - Torrassa',
    'ID_LINIA': 4,
    'CODI_LINIA': 1,
    'NOM_LINIA': 'L1',
    'ORDRE_LINIA': 1,
    'ORIGEN_SERVEI': 'Hospital de Bellvitge',
    'DESTI_SERVEI': 'Fondo',
    'DESC_SERVEI': 'Hospital de Bellvitge - Fondo',
    'ORDRE_TRAM': 7,
    'DATA': '2026-05-06Z',
    'COLOR_LINIA': 'CE1126',
    'ORIENTACIO_TEXT': 1,
    'LONGITUD': 549.269}},
  {'type': 'Feature',
   'id': 'TRAMS_LINIA.fid--7b6bcf9f_19e019dfb23_17d8',
   'geometry': {'type': 'MultiLineString',
    'coordinates': [[[2.11659379, 41.36839566],
      [2.1181193, 41.36841142],
      [2.11926124, 41.36842989],
      [2.12082456, 41.36844349],
      [2.12115749, 41.36843874],
      [2.12148948, 41.36841941],
      [2.12181943, 41.36838557],
      [2.1221462, 41.36833733],
      [2.12227951, 41.36831334],
      [2.12367402, 41.36804895],
      [2.12384301, 41.36801909],
      [2.12415948, 41.36797462],
      [2.12447889, 41.36794449],
      [2.12480012, 41.36792881],
      [2.12499773, 41.36792534],
      [2.12530111, 41.36793128],
      [2.12560337, 41.36795169],
      [2.12590331, 41.36798651],
      [2.12619973, 41.36803558],
      [2.1263088, 41.36805733],
      [2.12643363, 41.36808372],
      [2.1267885, 41.36816896],
      [2.12713703, 41.36826796],
      [2.12728915, 41.36831615],
      [2.12751775, 41.36839098],
      [2.12790677, 41.36852766],
      [2.12816747, 41.36862754],
      [2.1285194, 41.36877296],
      [2.12861721, 41.36881645]]]},
   'geometry_name': 'GEOMETRY',
   'properties': {'CODI_TRAM_LINIA': '117.118',
    'CODI_ESTACIO_INI': 117,
    'NOM_ESTACIO_INI': 'Torrassa',
    'CODI_ESTACIO_FI': 118,
    'NOM_ESTACIO_FI': 'Santa Eulàlia',
    'NOM_TRAM_LINIA': 'Torrassa - Santa Eulàlia',
    'ID_LINIA': 4,
    'CODI_LINIA': 1,
    'NOM_LINIA': 'L1',
    'ORDRE_LINIA': 1,
    'ORIGEN_SERVEI': 'Hospital de Bellvitge',
    'DESTI_SERVEI': 'Fondo',
    'DESC_SERVEI': 'Hospital de Bellvitge - Fondo',
    'ORDRE_TRAM': 8,
    'DATA': '2026-05-06Z',
    'COLOR_LINIA': 'CE1126',
    'ORIENTACIO_TEXT': 1,
    'LONGITUD': 1031.044}},
  {'type': 'Feature',
   'id': 'TRAMS_LINIA.fid--7b6bcf9f_19e019dfb23_17d9',
   'geometry': {'type': 'MultiLineString',
    'coordinates': [[[2.12861721, 41.36881645],
      [2.12975043, 41.36932905],
      [2.12982549, 41.36936595],
      [2.12998511, 41.36945177],
      [2.13017527, 41.36956705],
      [2.13032099, 41.36966832],
      [2.13046771, 41.36978628],
      [2.13061263, 41.36992236],
      [2.13065255, 41.36996257],
      [2.13234192, 41.37177],
      [2.13258956, 41.37202434],
      [2.13296126, 41.37238952],
      [2.13313273, 41.37256217],
      [2.13338729, 41.37283547],
      [2.13353699, 41.37300405]]]},
   'geometry_name': 'GEOMETRY',
   'properties': {'CODI_TRAM_LINIA': '118.119',
    'CODI_ESTACIO_INI': 118,
    'NOM_ESTACIO_INI': 'Santa Eulàlia',
    'CODI_ESTACIO_FI': 119,
    'NOM_ESTACIO_FI': 'Mercat Nou',
    'NOM_TRAM_LINIA': 'Santa Eulàlia - Mercat Nou',
    'ID_LINIA': 4,
    'CODI_LINIA': 1,
    'NOM_LINIA': 'L1',
    'ORDRE_LINIA': 1,
    'ORIGEN_SERVEI': 'Hospital de Bellvitge',
    'DESTI_SERVEI': 'Fondo',
    'DESC_SERVEI': 'Hospital de Bellvitge - Fondo',
    'ORDRE_TRAM': 9,
    'DATA': '2026-05-06Z',
    'COLOR_LINIA': 'CE1126',
    'ORIENTACIO_TEXT': 1,
    'LONGITUD': 629.385}},
  {'type': 'Feature',
   'id': 'TRAMS_LINIA.fid--7b6bcf9f_19e019dfb23_17da',
   'geometry': {'type': 'MultiLineString',
    'coordinates': [[[2.13353578, 41.3730027],
      [2.13384968, 41.37335209],
      [2.13410803, 41.37365548],
      [2.13426981, 41.37385886],
      [2.13442329, 41.37404317],
      [2.13467681, 41.37432046],
      [2.13476367, 41.37441078],
      [2.13492926, 41.37456373],
      [2.135001, 41.3746236],
      [2.13509442, 41.3746962],
      [2.13519732, 41.37476817],
      [2.13531918, 41.37484667],
      [2.13550154, 41.37494766],
      [2.13569476, 41.37503648],
      [2.13579578, 41.3750776],
      [2.13596803, 41.37514091],
      [2.13611096, 41.37518412],
      [2.13620892, 41.37521101],
      [2.13635773, 41.3752488],
      [2.13659957, 41.37529766],
      [2.13680247, 41.37532725],
      [2.13689841, 41.37533863],
      [2.13714736, 41.37535875],
      [2.13723536, 41.37536236],
      [2.13746925, 41.37536548],
      [2.13815393, 41.37535307]]]},
   'geometry_name': 'GEOMETRY',
   'properties': {'CODI_TRAM_LINIA': '119.120',
    'CODI_ESTACIO_INI': 119,
    'NOM_ESTACIO_INI': 'Mercat Nou',
    'CODI_ESTACIO_FI': 120,
    'NOM_ESTACIO_FI': 'Plaça de Sants',
    'NOM_TRAM_LINIA': 'Mercat Nou - Plaça de Sants',
    'ID_LINIA': 4,
    'CODI_LINIA': 1,
    'NOM_LINIA': 'L1',
    'ORDRE_LINIA': 1,
    'ORIGEN_SERVEI': 'Hospital de Bellvitge',
    'DESTI_SERVEI': 'Fondo',
    'DESC_SERVEI': 'Hospital de Bellvitge - Fondo',
    'ORDRE_TRAM': 10,
    'DATA': '2026-05-06Z',
    'COLOR_LINIA': 'CE1126',
    'ORIENTACIO_TEXT': 1,
    'LONGITUD': 504.053}},
  {'type': 'Feature',
   'id': 'TRAMS_LINIA.fid--7b6bcf9f_19e019dfb23_17db',
   'geometry': {'type': 'MultiLineString',
    'coordinates': [[[2.13815393, 41.37535307], [2.14329021, 41.37525364]]]},
   'geometry_name': 'GEOMETRY',
   'properties': {'CODI_TRAM_LINIA': '120.121',
    'CODI_ESTACIO_INI': 120,
    'NOM_ESTACIO_INI': 'Plaça de Sants',
    'CODI_ESTACIO_FI': 121,
    'NOM_ESTACIO_FI': 'Hostafrancs',
    'NOM_TRAM_LINIA': 'Plaça de Sants - Hostafrancs',
    'ID_LINIA': 4,
    'CODI_LINIA': 1,
    'NOM_LINIA': 'L1',
    'ORDRE_LINIA': 1,
    'ORIGEN_SERVEI': 'Hospital de Bellvitge',
    'DESTI_SERVEI': 'Fondo',
    'DESC_SERVEI': 'Hospital de Bellvitge - Fondo',
    'ORDRE_TRAM': 11,
    'DATA': '2026-05-06Z',
    'COLOR_LINIA': 'CE1126',
    'ORIENTACIO_TEXT': 1,
    'LONGITUD': 429.678}},
  {'type': 'Feature',
   'id': 'TRAMS_LINIA.fid--7b6bcf9f_19e019dfb23_17dc',
   'geometry': {'type': 'MultiLineString',
    'coordinates': [[[2.14329127, 41.37525362],
      [2.14758408, 41.37516968],
      [2.14784459, 41.37517112],
      [2.14801862, 41.37517657],
      [2.14825142, 41.37519674],
      [2.14848118, 41.37523152],
      [2.14867593, 41.37527313],
      [2.14876531, 41.37529489],
      [2.14885829, 41.37532077],
      [2.14890587, 41.37533573],
      [2.14909277, 41.37539807],
      [2.14936339, 41.3755016],
      [2.1493825, 41.37551004]]]},
   'geometry_name': 'GEOMETRY',
   'properties': {'CODI_TRAM_LINIA': '121.122',
    'CODI_ESTACIO_INI': 121,
    'NOM_ESTACIO_INI': 'Hostafrancs',
    'CODI_ESTACIO_FI': 122,
    'NOM_ESTACIO_FI': 'Espanya',
    'NOM_TRAM_LINIA': 'Hostafrancs - Espanya',
    'ID_LINIA': 4,
    'CODI_LINIA': 1,
    'NOM_LINIA': 'L1',
    'ORDRE_LINIA': 1,
    'ORIGEN_SERVEI': 'Hospital de Bellvitge',
    'DESTI_SERVEI': 'Fondo',
    'DESC_SERVEI': 'Hospital de Bellvitge - Fondo',
    'ORDRE_TRAM': 12,
    'DATA': '2026-05-06Z',
    'COLOR_LINIA': 'CE1126',
    'ORIENTACIO_TEXT': 1,
    'LONGITUD': 516.383}},
  {'type': 'Feature',
   'id': 'TRAMS_LINIA.fid--7b6bcf9f_19e019dfb23_17dd',
   'geometry': {'type': 'MultiLineString',
    'coordinates': [[[2.1493825, 41.37551004],
      [2.14962473, 41.37561784],
      [2.14983658, 41.3757251],
      [2.14989662, 41.37575785],
      [2.15009049, 41.37587531],
      [2.15024991, 41.37598742],
      [2.15456248, 41.37923215]]]},
   'geometry_name': 'GEOMETRY',
   'properties': {'CODI_TRAM_LINIA': '122.123',
    'CODI_ESTACIO_INI': 122,
    'NOM_ESTACIO_INI': 'Espanya',
    'CODI_ESTACIO_FI': 123,
    'NOM_ESTACIO_FI': 'Rocafort',
    'NOM_TRAM_LINIA': 'Espanya - Rocafort',
    'ID_LINIA': 4,
    'CODI_LINIA': 1,
    'NOM_LINIA': 'L1',
    'ORDRE_LINIA': 1,
    'ORIGEN_SERVEI': 'Hospital de Bellvitge',
    'DESTI_SERVEI': 'Fondo',
    'DESC_SERVEI': 'Hospital de Bellvitge - Fondo',
    'ORDRE_TRAM': 13,
    'DATA': '2026-05-06Z',
    'COLOR_LINIA': 'CE1126',
    'ORIENTACIO_TEXT': 1,
    'LONGITUD': 599.859}},
  {'type': 'Feature',
   'id': 'TRAMS_LINIA.fid--7b6bcf9f_19e019dfb23_17de',
   'geometry': {'type': 'MultiLineString',
    'coordinates': [[[2.15456248, 41.37923215], [2.15889091, 41.3824874]]]},
   'geometry_name': 'GEOMETRY',
   'properties': {'CODI_TRAM_LINIA': '123.124',
    'CODI_ESTACIO_INI': 123,
    'NOM_ESTACIO_INI': 'Rocafort',
    'CODI_ESTACIO_FI': 124,
    'NOM_ESTACIO_FI': 'Urgell',
    'NOM_TRAM_LINIA': 'Rocafort - Urgell',
    'ID_LINIA': 4,
    'CODI_LINIA': 1,
    'NOM_LINIA': 'L1',
    'ORDRE_LINIA': 1,
    'ORIGEN_SERVEI': 'Hospital de Bellvitge',
    'DESTI_SERVEI': 'Fondo',
    'DESC_SERVEI': 'Hospital de Bellvitge - Fondo',
    'ORDRE_TRAM': 14,
    'DATA': '2026-05-06Z',
    'COLOR_LINIA': 'CE1126',
    'ORIENTACIO_TEXT': 1,
    'LONGITUD': 511.489}},
  {'type': 'Feature',
   'id': 'TRAMS_LINIA.fid--7b6bcf9f_19e019dfb23_17df',
   'geometry': {'type': 'MultiLineString',
    'coordinates': [[[2.15889091, 41.3824874],
      [2.16179834, 41.38467396],
      [2.16183083, 41.3846975],
      [2.16197496, 41.38479467],
      [2.16203162, 41.38483061],
      [2.16217883, 41.38492026],
      [2.16239108, 41.38503747],
      [2.16256122, 41.38512239],
      [2.16268713, 41.38517887],
      [2.162947, 41.38529005],
      [2.1635684, 41.38553815],
      [2.16428386, 41.3858149]]]},
   'geometry_name': 'GEOMETRY',
   'properties': {'CODI_TRAM_LINIA': '124.125',
    'CODI_ESTACIO_INI': 124,
    'NOM_ESTACIO_INI': 'Urgell',
    'CODI_ESTACIO_FI': 125,
    'NOM_ESTACIO_FI': 'Universitat',
    'NOM_TRAM_LINIA': 'Urgell - Universitat',
    'ID_LINIA': 4,
    'CODI_LINIA': 1,
    'NOM_LINIA': 'L1',
    'ORDRE_LINIA': 1,
    'ORIGEN_SERVEI': 'Hospital de Bellvitge',
    'DESTI_SERVEI': 'Fondo',
    'DESC_SERVEI': 'Hospital de Bellvitge - Fondo',
    'ORDRE_TRAM': 15,
    'DATA': '2026-05-06Z',
    'COLOR_LINIA': 'CE1126',
    'ORIENTACIO_TEXT': 1,
    'LONGITUD': 587.908}},
  {'type': 'Feature',
   'id': 'TRAMS_LINIA.fid--7b6bcf9f_19e019dfb23_17e0',
   'geometry': {'type': 'MultiLineString',
    'coordinates': [[[2.16428386, 41.3858149],
      [2.16470857, 41.38597553],
      [2.16488101, 41.38603461],
      [2.16510183, 41.38609987],
      [2.16516065, 41.38612071],
      [2.16535508, 41.38618394],
      [2.16539433, 41.38619801],
      [2.16679558, 41.38672422],
      [2.16735587, 41.38692956],
      [2.16807472, 41.38720091],
      [2.16822893, 41.38725716],
      [2.16848249, 41.38733879],
      [2.16888599, 41.38745424],
      [2.1689946, 41.38748943]]]},
   'geometry_name': 'GEOMETRY',
   'properties': {'CODI_TRAM_LINIA': '125.126',
    'CODI_ESTACIO_INI': 125,
    'NOM_ESTACIO_INI': 'Universitat',
    'CODI_ESTACIO_FI': 126,
    'NOM_ESTACIO_FI': 'Catalunya',
    'NOM_TRAM_LINIA': 'Universitat - Catalunya',
    'ID_LINIA': 4,
    'CODI_LINIA': 1,
    'NOM_LINIA': 'L1',
    'ORDRE_LINIA': 1,
    'ORIGEN_SERVEI': 'Hospital de Bellvitge',
    'DESTI_SERVEI': 'Fondo',
    'DESC_SERVEI': 'Hospital de Bellvitge - Fondo',
    'ORDRE_TRAM': 16,
    'DATA': '2026-05-06Z',
    'COLOR_LINIA': 'CE1126',
    'ORIENTACIO_TEXT': 1,
    'LONGITUD': 435.804}},
  {'type': 'Feature',

In [8]:
df_trajectories = []
for trajectory in trajectories['features']:
    properties = trajectory.get('properties', {})
    nom_estacio_fi = properties.get('NOM_ESTACIO_FI')
    nom_linia = properties.get('NOM_LINIA')
    
    if nom_estacio_fi in stops and nom_linia == 'L3':
        df_trajectories.append({
            'name': nom_estacio_fi,
            'geometry': shape(trajectory['geometry'])
        })
df_trajectories

[{'name': 'Palau Reial',
  'geometry': <MULTILINESTRING ((2.111 41.384, 2.112 41.384, 2.115 41.385, 2.115 41.385, 2...>},
 {'name': 'Maria Cristina',
  'geometry': <MULTILINESTRING ((2.119 41.386, 2.126 41.388))>},
 {'name': 'Les Corts',
  'geometry': <MULTILINESTRING ((2.126 41.388, 2.126 41.388, 2.127 41.388, 2.127 41.388, 2...>},
 {'name': 'Plaça del Centre',
  'geometry': <MULTILINESTRING ((2.131 41.384, 2.131 41.384, 2.131 41.383, 2.131 41.383, 2...>},
 {'name': 'Sants Estació',
  'geometry': <MULTILINESTRING ((2.136 41.382, 2.138 41.383, 2.138 41.383, 2.138 41.383, 2...>},
 {'name': 'Tarragona',
  'geometry': <MULTILINESTRING ((2.141 41.382, 2.142 41.381, 2.142 41.381, 2.142 41.381, 2...>},
 {'name': 'Espanya',
  'geometry': <MULTILINESTRING ((2.145 41.378, 2.149 41.376, 2.149 41.376, 2.149 41.375, 2...>},
 {'name': 'Poble Sec',
  'geometry': <MULTILINESTRING ((2.152 41.375, 2.152 41.375, 2.154 41.375, 2.157 41.375, 2...>},
 {'name': 'Paral·lel',
  'geometry': <MULTILINESTRING ((2.16 41.375, 2.164 41.375, 2.164 41.375, 2.165 41.375, 2....>},
 {'name': 'Drassanes',
  'geometry': <MULTILINESTRING ((2.169 41.375, 2.172 41.375, 2.172 41.375, 2.172 41.375, 2...>},
 {'name': 'Liceu',
  'geometry': <MULTILINESTRING ((2.176 41.377, 2.176 41.377, 2.176 41.377, 2.176 41.377, 2...>},
 {'name': 'Catalunya',
  'geometry': <MULTILINESTRING ((2.173 41.381, 2.172 41.383, 2.172 41.383, 2.172 41.383, 2...>}]

In [9]:
df_trajectories = pd.DataFrame(df_trajectories)
geo_df_trajectories = gpd.GeoDataFrame(df_trajectories, geometry='geometry')
geo_df_trajectories

                name                                           geometry
0        Palau Reial  MULTILINESTRING ((2.11118 41.38412, 2.11238 41...
1     Maria Cristina  MULTILINESTRING ((2.11854 41.38598, 2.12579 41...
2          Les Corts  MULTILINESTRING ((2.12579 41.38782, 2.12632 41...
3   Plaça del Centre  MULTILINESTRING ((2.13087 41.38412, 2.13114 41...
4      Sants Estació  MULTILINESTRING ((2.13588 41.38192, 2.13776 41...
5          Tarragona  MULTILINESTRING ((2.14099 41.3816, 2.14155 41....
6            Espanya  MULTILINESTRING ((2.14534 41.37849, 2.14921 41...
7          Poble Sec  MULTILINESTRING ((2.15155 41.37502, 2.15219 41...
8          Paral·lel  MULTILINESTRING ((2.16024 41.375, 2.16385 41.3...
9          Drassanes  MULTILINESTRING ((2.16912 41.37489, 2.17167 41...
10             Liceu  MULTILINESTRING ((2.17566 41.37654, 2.17597 41...
11         Catalunya  MULTILINESTRING ((2.17303 41.38145, 2.172 41.3...

# Neighbourhoods

In [10]:
neigh = pd.read_csv("data/neigh.csv")

neigh["geometry"] = neigh["geom"].apply(wkt.loads)

neigh = gpd.GeoDataFrame(
    neigh,
    geometry="geometry",
    crs="EPSG:4326"
)
neigh = neigh[["name", "geometry"]]
neigh["geometry"] = neigh.buffer(0)

In [11]:
geo_df_trajectories

                name                                           geometry
0        Palau Reial  MULTILINESTRING ((2.11118 41.38412, 2.11238 41...
1     Maria Cristina  MULTILINESTRING ((2.11854 41.38598, 2.12579 41...
2          Les Corts  MULTILINESTRING ((2.12579 41.38782, 2.12632 41...
3   Plaça del Centre  MULTILINESTRING ((2.13087 41.38412, 2.13114 41...
4      Sants Estació  MULTILINESTRING ((2.13588 41.38192, 2.13776 41...
5          Tarragona  MULTILINESTRING ((2.14099 41.3816, 2.14155 41....
6            Espanya  MULTILINESTRING ((2.14534 41.37849, 2.14921 41...
7          Poble Sec  MULTILINESTRING ((2.15155 41.37502, 2.15219 41...
8          Paral·lel  MULTILINESTRING ((2.16024 41.375, 2.16385 41.3...
9          Drassanes  MULTILINESTRING ((2.16912 41.37489, 2.17167 41...
10             Liceu  MULTILINESTRING ((2.17566 41.37654, 2.17597 41...
11         Catalunya  MULTILINESTRING ((2.17303 41.38145, 2.172 41.3...

In [12]:
geo_df_stops

                  name   stop_type                  geometry
0              Espanya       Metro  POINT (2.14939 41.37546)
1            Catalunya       Metro  POINT (2.16972 41.38771)
2            Paral·lel       Metro  POINT (2.16903 41.37458)
3          Palau Reial       Metro  POINT (2.11854 41.38598)
4       Maria Cristina       Metro  POINT (2.12579 41.38782)
5            Les Corts       Metro  POINT (2.13087 41.38412)
6     Plaça del Centre       Metro  POINT (2.13588 41.38192)
7        Sants Estació       Metro  POINT (2.14189 41.38096)
8            Tarragona       Metro  POINT (2.14534 41.37849)
9            Poble Sec       Metro    POINT (2.16024 41.375)
10           Drassanes       Metro  POINT (2.17566 41.37654)
11               Liceu       Metro  POINT (2.17303 41.38145)
12   Ronda Universitat         Bus  POINT (2.16734 41.38704)
13        Plaça Tetuan         Bus   POINT (2.17683 41.3961)
14                 Fib  University  POINT (2.11303 41.38913)
15         Belles Arts  University  POINT (2.11406 41.38275)
16        Arquitectura  University  POINT (2.11367 41.38407)
17                 FME  University  POINT (2.11565 41.38484)
18  Economia i Empresa  University  POINT (2.11432 41.38591)
19                Dret  University  POINT (2.12069 41.38748)

In [13]:
geo_df_trajectories

                name                                           geometry
0        Palau Reial  MULTILINESTRING ((2.11118 41.38412, 2.11238 41...
1     Maria Cristina  MULTILINESTRING ((2.11854 41.38598, 2.12579 41...
2          Les Corts  MULTILINESTRING ((2.12579 41.38782, 2.12632 41...
3   Plaça del Centre  MULTILINESTRING ((2.13087 41.38412, 2.13114 41...
4      Sants Estació  MULTILINESTRING ((2.13588 41.38192, 2.13776 41...
5          Tarragona  MULTILINESTRING ((2.14099 41.3816, 2.14155 41....
6            Espanya  MULTILINESTRING ((2.14534 41.37849, 2.14921 41...
7          Poble Sec  MULTILINESTRING ((2.15155 41.37502, 2.15219 41...
8          Paral·lel  MULTILINESTRING ((2.16024 41.375, 2.16385 41.3...
9          Drassanes  MULTILINESTRING ((2.16912 41.37489, 2.17167 41...
10             Liceu  MULTILINESTRING ((2.17566 41.37654, 2.17597 41...
11         Catalunya  MULTILINESTRING ((2.17303 41.38145, 2.172 41.3...

In [14]:
neigh_layer = alt.Chart(neigh).mark_geoshape(
    stroke="black",
    fill="lightblue"
).properties(
    width=600,
    height=600
    
).encode(tooltip=['name'])

trajectory_layer = alt.Chart(geo_df_trajectories).mark_geoshape(
    stroke="green",
    filled = False,
    strokeWidth=3).encode(tooltip=['name']
).properties(
    width=600,
    height=600
)

point_layer = alt.Chart(geo_df_stops).mark_geoshape(
    stroke="black",size=0).encode(tooltip=['name'],color = alt.Color('stop_type:N', scale=alt.Scale(domain=['Metro', 'Bus', 'University'], range=['green', 'blue', 'orange'])))
neigh_layer + trajectory_layer + point_layer

alt.LayerChart(...)

# All Stops

In [14]:
df_stops_all = []
for stop in data['features']:
    properties = stop.get('properties', {})
    nom_estacio = properties.get('NOM_ESTACIO')
    linia = properties.get('PICTO')
    df_stops_all.append({
            'name': nom_estacio,
            'linia': linia,
            'stop_type': 'Metro',
            'geometry': shape(stop['geometry'])
        })

df_stops_all.append({
    'name': 'Ronda Universitat',
    'stop_type': 'Bus',
    'geometry': point1
})

df_stops_all.append({
    'name': 'Plaça Tetuan',
    'stop_type': 'Bus',
    'geometry': point2
})

geo_df_stops_all = gpd.GeoDataFrame(df_stops_all, geometry='geometry')
excluded = ['FM','L10N','L10S','L11','L9N','L9S','L9NL10N','L9SL10S','TM']
geo_df_stops_all = geo_df_stops_all[~geo_df_stops_all['linia'].isin(excluded)]
geo_df_stops_all

                       name linia stop_type                  geometry
0     Hospital de Bellvitge    L1     Metro  POINT (2.10724 41.34468)
1                 Bellvitge    L1     Metro  POINT (2.11092 41.35097)
2              Av. Carrilet    L1     Metro  POINT (2.10265 41.35852)
3      Rambla Just Oliveras    L1     Metro  POINT (2.09975 41.36409)
4                 Can Serra    L1     Metro  POINT (2.10275 41.36769)
..                      ...   ...       ...                       ...
102               El Carmel    L5     Metro   POINT (2.1551 41.42445)
103  El Coll | La Teixonera    L5     Metro    POINT (2.14835 41.422)
104            Ernest Lluch    L5     Metro   POINT (2.11203 41.3759)
140       Ronda Universitat   NaN       Bus  POINT (2.16734 41.38704)
141            Plaça Tetuan   NaN       Bus   POINT (2.17683 41.3961)

[107 rows x 4 columns]

# All trajectories

In [21]:
df_trajectories_all = []
for trajectory in trajectories['features']:
    properties = trajectory.get('properties', {})
    tram = properties.get('NOM_TRAM_LINIA')
    nom_linia = properties.get('NOM_LINIA')
    df_trajectories_all.append({
            'tram': tram,
            'linia': nom_linia,
            'geometry': shape(trajectory['geometry'])
        })
df_trajectories_all = pd.DataFrame(df_trajectories_all)
geo_df_trajectories_all = gpd.GeoDataFrame(df_trajectories_all, geometry='geometry')
geo_df_trajectories_all = geo_df_trajectories_all[~geo_df_trajectories_all['linia'].isin(excluded)]
geo_df_trajectories_all = geo_df_trajectories_all[geo_df_trajectories_all['tram'].str.contains('Inici') == False]
geo_df_trajectories_all = geo_df_trajectories_all[geo_df_trajectories_all['tram'].str.contains('Final') == False]

In [22]:
sol1 = shape({
    'type': 'Point',
    'coordinates':  (2.1319539025975986, 41.389541783812525)
})

sol2 = shape({
    'type': 'Point',
    'coordinates':  (2.1991779497207844, 41.404303976357355)
})

sol_df = pd.DataFrame({
    'name': ['Sol','Sol'],
    'stop_type': ['Bus', 'Bus'],
    'geometry': [sol1, sol2]
})
sol_df = gpd.GeoDataFrame(sol_df, geometry='geometry')

In [23]:
sol_df_buffer = sol_df.copy()
sol_df_buffer["geometry"] = sol_df_buffer.buffer(0.007)
sol_df_buffer

  name stop_type                                           geometry
0  Sol       Bus  POLYGON ((2.13895 41.38954, 2.13892 41.38886, ...
1  Sol       Bus  POLYGON ((2.20618 41.4043, 2.20614 41.40362, 2...

In [24]:
trajectory_layer = alt.Chart(geo_df_trajectories_all).mark_geoshape(
    strokeWidth=3,filled = False).encode(
        color=alt.Color('linia:N',scale = alt.Scale(domain=['L1', 'L2', 'L3','L4','L5'], range=['red', 'purple', 'green','yellow','blue']))).properties(
    width=600,
    height=600
)

point_layer = alt.Chart(geo_df_stops_all).mark_geoshape(
    stroke="black").encode(tooltip=['name'],color = alt.Color('stop_type:N', scale=alt.Scale(domain=['Metro', 'Bus'], range=['green', 'blue'])))

sol_point_layer = alt.Chart(sol_df).mark_geoshape(
    stroke="black",size=0,color='black')

buffer_layer = alt.Chart(sol_df_buffer).mark_geoshape(
    stroke="black",color='lightgrey',fillOpacity=0
)



(neigh_layer + trajectory_layer + point_layer + sol_point_layer + buffer_layer).resolve_scale(color='independent')

alt.LayerChart(...)