In [76]:
import pandas as pd
import geopandas as gpd
import json
from shapely.geometry import shape
from shapely import wkt
import warnings
from shapely.ops import linemerge, unary_union

# filter all warnings
warnings.filterwarnings("ignore")

In [77]:
neigh = pd.read_csv("Data/Neigh/neigh.csv")

neigh["geometry"] = neigh["geom"].apply(wkt.loads)

neigh = gpd.GeoDataFrame(
    neigh,
    geometry="geometry",
    crs="EPSG:4326"
)
neigh = neigh[["name", "geometry"]]
neigh["geometry"] = neigh.buffer(0)

In [78]:
with open('data/Bus/AMB.json') as f:
    data = json.load(f)


stops_amb = []
traj_amb = []

for collection in data:
    for feature in collection["features"]:
        props = feature["properties"]
        geom = feature["geometry"]
        if geom["type"] == "Point":
            stops_amb.append({
                "code": props["COD_EMT"],
                "name": props["NOMBRE"],
                "geometry": shape(geom)
            })
        if geom["type"] != "Point":
            traj_amb.append({
                "linia": props["LINEA"],
                "sentit": props["SENTIDO"],
                "geometry": shape(geom)
            })

geo_df_stops_amb = gpd.GeoDataFrame(stops_amb,geometry="geometry", crs="EPSG:4326")
geo_df_traj_amb = gpd.GeoDataFrame(traj_amb, geometry="geometry", crs="EPSG:4326")


buffered = neigh.copy()
buffered.to_crs('EPSG:25831', inplace=True)
buffered["geometry"] = buffered.geometry.buffer(2500)
geo_df_stops_amb.to_crs('EPSG:25831', inplace=True)
geo_df_stops_amb = gpd.sjoin(
    geo_df_stops_amb,
    buffered[["geometry"]],
    predicate="within",
    how="inner",
).drop(columns="index_right")
geo_df_stops_amb.to_crs('EPSG:4326', inplace=True)

geo_df_traj_amb = (geo_df_traj_amb.groupby("linia", as_index=False).agg(geometry=("geometry", lambda s: unary_union(list(s)))))

geo_df_traj_amb = gpd.GeoDataFrame(geo_df_traj_amb,geometry="geometry",crs="EPSG:4326")

boundary = buffered.union_all()
geo_df_traj_amb.to_crs('EPSG:25831', inplace=True)
geo_df_traj_amb["inside_ratio"] = (
    geo_df_traj_amb.geometry.intersection(boundary).length
    / geo_df_traj_amb.geometry.length
)

geo_df_traj_amb = geo_df_traj_amb[
    geo_df_traj_amb["inside_ratio"] >= 0.60   # keep lines with >=20% inside
]


geo_df_traj_amb.to_crs('EPSG:4326', inplace=True)
geo_df_traj_amb.drop_duplicates(subset=['linia'],inplace=True)
geo_df_stops_amb.drop_duplicates(subset=['code'],inplace=True)

In [79]:
# delete all the zeros before the bus stop code
geo_df_stops_amb["code"] = geo_df_stops_amb["code"].apply(lambda x: x.lstrip("0")).astype(int)
geo_df_stops_amb

         code                       name                  geometry
223    200103                Riera Bonet  POINT (2.02769 41.40477)
267    200152      Esglesia St. Bartomeu  POINT (2.03807 41.42635)
268    200178      Esglesia St. Bartomeu  POINT (2.03821 41.42648)
277    200153       Ctra. de Vallvidrera  POINT (2.04046 41.42781)
300    105724     Roserar Dot i Camprubi  POINT (2.04579 41.39055)
...       ...                        ...                       ...
12809  107905  Poliesportiu Marina Besos  POINT (2.23174 41.42347)
12813  102334            Salvador Espriu  POINT (2.23246 41.44564)
12815  110367           Tortosa - Guifre  POINT (2.23514 41.43701)
12823  107908                    La Mora  POINT (2.23756 41.43223)
12824  110368    Industria - Antoni Bori  POINT (2.23854 41.43733)

[3462 rows x 3 columns]

In [80]:
bus_stops_w_line = pd.read_excel("Data/Bus/all_lines.xlsx")
bus_stops_w_line.rename(columns={"Código de parada / Codi de parada": "code",'Municipio / Municipi': 'municipi','Líneas / Línies': 'lines'}, inplace=True)
bus_stops_w_line = bus_stops_w_line[["code", "municipi", "lines"]]
geo_df_stops_amb = geo_df_stops_amb.merge(bus_stops_w_line, on="code", how="left")
geo_df_stops_amb = geo_df_stops_amb[geo_df_stops_amb["lines"].notnull()]
geo_df_stops_amb["lines"] = geo_df_stops_amb["lines"].apply(lambda x: [line.strip() for line in x.split("-")])
geo_df_stops_amb = geo_df_stops_amb.explode("lines", ignore_index=True)
# delete lines that start with N
geo_df_stops_amb = geo_df_stops_amb[~geo_df_stops_amb["lines"].str.startswith("N")]
geo_df_stops_amb['lines'].nunique(), geo_df_stops_amb['code'].nunique()

(187, 3137)

In [81]:
linies_w_trajectory = geo_df_traj_amb["linia"].unique().tolist()
geo_df_traj_amb["linia"].nunique()

156

In [82]:
geo_df_stops_amb = geo_df_stops_amb[geo_df_stops_amb["lines"].isin(linies_w_trajectory)]

In [83]:
geo_df_stops_amb['lines'].nunique(), geo_df_stops_amb['code'].nunique()

(132, 2939)

In [86]:
geo_df_stops_amb[geo_df_stops_amb['lines'] == 'V33'].sort_values(by='name', ascending=True)

,code,name,geometry,municipi,lines
5021,3598,Alfons el Magnanim - Jaume Huguet,POINT (2.21249 41.41786),Barcelona,V33
5022,3597,Alfons el Magnanim - Jaume Huguet,POINT (2.21258 41.41805),Barcelona,V33
5026,2660,Argentina - Bernat Metge,POINT (2.21263 41.42129),Sant Adrià de Besòs,V33
3259,2577,Argentina - Bernat Metge,POINT (2.21275 41.42147),Sant Adrià de Besòs,V33
3217,84,Av Santa Coloma,POINT (2.20788 41.44818),Santa Coloma de Gramenet,V33
7097,729,Balmes - Alarcon,POINT (2.21087 41.42963),Sant Adrià de Besòs,V33
7070,728,Balmes - Almirall Oquendo,POINT (2.20774 41.43115),Sant Adrià de Besòs,V33
3266,967,Balmes - Jovellanos,POINT (2.21032 41.43012),Sant Adrià de Besòs,V33
8366,968,Balmes - Pereda,POINT (2.20789 41.43133),Sant Adrià de Besòs,V33
3331,666,Banus - Metro Santa Rosa,POINT (2.21405 41.44632),Santa Coloma de Gramenet,V33
3255,1666,Bernat Metge - Argentina,POINT (2.21177 41.42019),Barcelona,V33
7094,1699,Bernat Metge - Rambla Prim,POINT (2.2119 41.42046),Barcelona,V33
3280,663,Can Peixauet,POINT (2.21081 41.44472),Santa Coloma de Gramenet,V33
4944,3750,Caracas - Cuzco,POINT (2.2035 41.44065),Barcelona,V33
6206,1454,Caracas - Pl Celesti Boada,POINT (2.20362 41.43931),Barcelona,V33
3077,159,Caracas - Potosi,POINT (2.20269 41.44406),Barcelona,V33
4915,3761,Ciutat d'Asuncion - Ferran Junoy,POINT (2.19848 41.44598),Barcelona,V33
3041,1455,Ciutat d'Asuncion - Potosi,POINT (2.19982 41.44167),Barcelona,V33
4920,1659,Ciutat d'Asuncion - Tucuman,POINT (2.19926 41.44459),Barcelona,V33
5061,3556,Cristobal de Moura-Perpinya,POINT (2.2158 41.41791),Barcelona,V33
5058,3547,Cristobal de Moura-Perpinya,POINT (2.21556 41.41799),Barcelona,V33
5030,506,Extremadura - Ctra de Mataro,POINT (2.211 41.42355),Sant Adrià de Besòs,V33
3205,3689,Extremadura - Guipuscoa,POINT (2.20943 41.42517),Sant Adrià de Besòs,V33
3201,3688,Extremadura - Guipuscoa,POINT (2.20925 41.42476),Barcelona,V33
6277,569,Extremadura - Pl Clementina Arderiu,POINT (2.21127 41.42249),Barcelona,V33
5087,3405,Irlanda,POINT (2.21459 41.44869),Santa Coloma de Gramenet,V33
5083,3655,Irlanda - Mossen Jacint Verdaguer,POINT (2.21497 41.44766),Santa Coloma de Gramenet,V33
3348,3596,La Mina - Ponent,POINT (2.21778 41.41812),Sant Adrià de Besòs,V33
7563,2230,La Mina - Ponent,POINT (2.2173 41.41835),Sant Adrià de Besòs,V33
3265,899,La Verneda - Poligon Montsolis,POINT (2.21107 41.42683),Sant Adrià de Besòs,V33
5035,1744,La Verneda - Poligon Montsolis,POINT (2.21048 41.42683),Sant Adrià de Besòs,V33
7062,1780,Lima - Caracas,POINT (2.20448 41.43923),Barcelona,V33
3035,603,Lima - Ciutat d'Asuncion,POINT (2.20079 41.4392),Barcelona,V33
5002,12,Llinars - Santander,POINT (2.20731 41.43475),Barcelona,V33
4976,1336,Llorenc Serra,POINT (2.20399 41.44988),Santa Coloma de Gramenet,V33
3156,838,Llorenc Serra,POINT (2.20518 41.45046),Santa Coloma de Gramenet,V33
3289,3406,Mercat Sagarra,POINT (2.21236 41.45068),Santa Coloma de Gramenet,V33
3211,85,Metro Can Peixauet,POINT (2.20961 41.44493),Santa Coloma de Gramenet,V33
3223,2575,Metro Sta. Coloma,POINT (2.20681 41.45051),Santa Coloma de Gramenet,V33
3050,1418,Pg Santa Coloma - Baro de Viver,POINT (2.19974 41.44857),Barcelona,V33
7060,969,Pg Enric Sanchis - Sant Adria,POINT (2.20485 41.43552),Barcelona,V33
3146,970,Pg Enric Sanchis - Santander,POINT (2.20597 41.4335),Barcelona,V33
7072,1453,Pg Guayaquil - Arbeca,POINT (2.2081 41.43949),Barcelona,V33
6253,1101,Pl. Vila - Metro Sta. Coloma,POINT (2.20815 41.45116),Santa Coloma de Gramenet,V33
6240,588,Sant Adria - Bon Pastor,POINT (2.2079 41.43648),Barcelona,V33
7564,3595,Sant Ramon de Penyafort - Av Eduard Maristany,POINT (2.22096 41.41384),Barcelona,V33
8370,3336,Sant Ramon de Penyafort - Manuel Fernandez Mar...,POINT (2.21938 41.41581),Sant Adrià de Besòs,V33
3150,13,Sas - Claramunt,POINT (2.20418 41.43759),Barcelona,V33
5122,2750,St. Ramon de Penyafort - Manuel Fernandez Marquez,POINT (2.21969 41.41501),Barcelona,V33
3080,2394,Tiana - Campins,POINT (2.20095 41.44764),Barcelona,V33