In [28]:
import pandas as pd
import geopandas as gpd
import json
from shapely.geometry import shape, Point
from shapely import wkt
import warnings
from shapely.ops import linemerge, unary_union
import altair as alt
alt.data_transformers.disable_max_rows()

# filter all warnings
warnings.filterwarnings("ignore")

In [29]:
neigh = pd.read_csv("Data/Neigh/neigh.csv")

neigh["geometry"] = neigh["geom"].apply(wkt.loads)

neigh = gpd.GeoDataFrame(
    neigh,
    geometry="geometry",
    crs="EPSG:4326"
)
neigh = neigh[["name", "geometry"]]
neigh["geometry"] = neigh.buffer(0)

neigh_layer = alt.Chart(neigh).mark_geoshape(
    stroke="black",
    fill="lightblue"
).properties(
    width=600,
    height=600
    
).encode(tooltip=['name'])

In [30]:
with open('data/Bus/AMB.json') as f:
    data = json.load(f)


stops_amb = []
traj_amb = []

for collection in data:
    for feature in collection["features"]:
        props = feature["properties"]
        geom = feature["geometry"]
        if geom["type"] == "Point":
            stops_amb.append({
                "code": props["COD_EMT"],
                "name": props["NOMBRE"],
                "geometry": shape(geom)
            })
        if geom["type"] != "Point":
            traj_amb.append({
                "linia": props["LINEA"],
                "sentit": props["SENTIDO"],
                "geometry": shape(geom)
            })

geo_df_stops_amb = gpd.GeoDataFrame(stops_amb,geometry="geometry", crs="EPSG:4326")
geo_df_traj_amb = gpd.GeoDataFrame(traj_amb, geometry="geometry", crs="EPSG:4326")


buffered = neigh.copy()
buffered.to_crs('EPSG:25831', inplace=True)
buffered["geometry"] = buffered.geometry.buffer(2500)
# geo_df_stops_amb.to_crs('EPSG:25831', inplace=True)
# geo_df_stops_amb = gpd.sjoin(
#     geo_df_stops_amb,
#     buffered[["geometry"]],
#     predicate="within",
#     how="inner",
# ).drop(columns="index_right")
# geo_df_stops_amb.to_crs('EPSG:4326', inplace=True)

geo_df_traj_amb = (geo_df_traj_amb.groupby("linia", as_index=False).agg(geometry=("geometry", lambda s: unary_union(list(s)))))

geo_df_traj_amb = gpd.GeoDataFrame(geo_df_traj_amb,geometry="geometry",crs="EPSG:4326")

boundary = buffered.union_all()
geo_df_traj_amb.to_crs('EPSG:25831', inplace=True)
geo_df_traj_amb["inside_ratio"] = (
    geo_df_traj_amb.geometry.intersection(boundary).length
    / geo_df_traj_amb.geometry.length
)


print(geo_df_traj_amb[geo_df_traj_amb['linia'] == '102'])


geo_df_traj_amb = geo_df_traj_amb[
    geo_df_traj_amb["inside_ratio"] >= 0.6   # keep lines with >=20% inside
]


geo_df_traj_amb.to_crs('EPSG:4326', inplace=True)
geo_df_traj_amb.drop_duplicates(subset=['linia'],inplace=True)
geo_df_stops_amb.drop_duplicates(subset=['code'],inplace=True)

  linia                                           geometry  inside_ratio
0   102  MULTILINESTRING ((429790.259 4590539.249, 4297...           1.0

In [31]:
# delete all the zeros before the bus stop code
geo_df_stops_amb["code"] = geo_df_stops_amb["code"].apply(lambda x: x.lstrip("0")).astype(int)
geo_df_stops_amb

         code                         name                  geometry
0      105083   Pg. Maritim - Port Ginesta  POINT (1.93085 41.26248)
1      109141        Pg. Maritim - Uruguai  POINT (1.94473 41.26459)
2      106979      Joan Maragall - escales  POINT (1.94449 41.27091)
3      107017   Av. del Poal - Comte Guell  POINT (1.94613 41.27432)
4      201017                    Osona, 33  POINT (1.94221 41.40663)
...       ...                          ...                       ...
12836  110371           Industria - Ponent  POINT (2.24013 41.43871)
12840  110494                       Bufala  POINT (2.24146 41.45804)
12852  108835            Parc de la Bobila  POINT (2.24467 41.46023)
12888  106055                Can Puigcarbo  POINT (2.26386 41.48403)
12917  106037  La Virreina - Ciutat Comtal  POINT (2.27951 41.47576)

[4915 rows x 3 columns]

In [32]:
bus_stops_w_line = pd.read_excel("Data/Bus/all_lines.xlsx")
len(bus_stops_w_line[bus_stops_w_line['Código de parada / Codi de parada'] == 2275])

1

In [33]:
geo_df_stops_amb

         code                         name                  geometry
0      105083   Pg. Maritim - Port Ginesta  POINT (1.93085 41.26248)
1      109141        Pg. Maritim - Uruguai  POINT (1.94473 41.26459)
2      106979      Joan Maragall - escales  POINT (1.94449 41.27091)
3      107017   Av. del Poal - Comte Guell  POINT (1.94613 41.27432)
4      201017                    Osona, 33  POINT (1.94221 41.40663)
...       ...                          ...                       ...
12836  110371           Industria - Ponent  POINT (2.24013 41.43871)
12840  110494                       Bufala  POINT (2.24146 41.45804)
12852  108835            Parc de la Bobila  POINT (2.24467 41.46023)
12888  106055                Can Puigcarbo  POINT (2.26386 41.48403)
12917  106037  La Virreina - Ciutat Comtal  POINT (2.27951 41.47576)

[4915 rows x 3 columns]

In [34]:
geo_df_stops_amb[geo_df_stops_amb['name'].str.startswith("Major - Pl")]

     code                    name                  geometry
318  2275  Major - Pl Constitucio  POINT (2.05493 41.36687)

In [35]:
bus_stops_w_line = pd.read_excel("Data/Bus/all_lines.xlsx")
bus_stops_w_line

,Código de parada / Codi de parada,Nombre / Nom,Municipio / Municipi,UTM X,UTM Y,Mobiliario / Mobiliari,Adaptada,Líneas / Línies
0,2,Av Icària - Àlaba,Barcelona,"433034,9710","4582706,3560",Marquesina,No Adaptada,59 - N8 - H16 - V27
1,3,València - Muntaner,Barcelona,"429594,5550","4582232,9080",Marquesina,Adaptada,63 - N7 - H10
2,4,Mallorca - Balmes,Barcelona,"429667,5360","4582506,9960",Marquesina,No Adaptada,H10
3,7,Pl Universitat,Barcelona,"430044,7920","4581935,5410",Marquesina,Adaptada,N1 - N12 - N15 - N17 - N2 - H12 - N18 - N28 - 52
4,8,Pl de Carles Buïgas,Barcelona,"428925,6260","4580296,3200",Marquesina,No Adaptada,13 - X3 - 150
...,...,...,...,...,...,...,...,...
5222,201607,Av. Bertomeu - Pintor Fortuny,Cerdanyola del Vallès,"423785,0000","4594367,0000",NaN,No Adaptada,CV2
5223,201608,Av. Bertomeu - Pintor Fortuny,Cerdanyola del Vallès,"423789,0000","4594375,0000",NaN,No Adaptada,CV2
5224,201611,Les Forques,El Papiol,"416877,7760","4587252,2500",NaN,Adaptada,PA2
5225,201612,Enric Granados - Narcís Monturiol,El Papiol,"417033,2250","4587043,4470",NaN,Adaptada,PA2
5226,201613,Polígon Industrial,El Papiol,"417327,5800","4587101,1710",NaN,Adaptada,PA2

In [36]:
bus_stops_w_line = pd.read_excel("Data/Bus/all_lines.xlsx")
bus_stops_w_line.rename(columns={"Código de parada / Codi de parada": "code",'Municipio / Municipi': 'municipi','Líneas / Línies': 'lines','UTM X': 'utm_x','UTM Y': 'utm_y','Nombre / Nom':'name'}, inplace=True)
bus_stops_w_line["utm_x"] = pd.to_numeric(
    bus_stops_w_line["utm_x"].astype(str).str.replace(",", ".", regex=False),
    errors="coerce"
)

bus_stops_w_line["utm_y"] = pd.to_numeric(
    bus_stops_w_line["utm_y"].astype(str).str.replace(",", ".", regex=False),
    errors="coerce"
)

geo_df_stops_amb = gpd.GeoDataFrame(
    bus_stops_w_line,
    geometry=gpd.points_from_xy(bus_stops_w_line["utm_x"], bus_stops_w_line["utm_y"]),
    crs="EPSG:25831"
)
geo_df_stops_amb.drop(columns=["utm_x", "utm_y",'Mobiliario / Mobiliari','Adaptada'], inplace=True) 
geo_df_stops_amb.to_crs('EPSG:4326', inplace=True)
geo_df_stops_amb = geo_df_stops_amb[geo_df_stops_amb["lines"].notnull()]
geo_df_stops_amb["lines"] = geo_df_stops_amb["lines"].apply(lambda x: [line.strip() for line in x.split("-")])
geo_df_stops_amb = geo_df_stops_amb.explode("lines", ignore_index=True)
geo_df_stops_amb = geo_df_stops_amb[~geo_df_stops_amb["lines"].str.startswith("N")] # treure bus nits
geo_df_stops_amb = geo_df_stops_amb[geo_df_stops_amb["lines"].isin(['A1','A2','MB3','PR4','JT','135','198','197']) == False] # treure bus aeroport
geo_df_stops_amb['lines'].nunique(), geo_df_stops_amb['code'].nunique()
geo_df_stops_amb

,code,name,municipi,lines,geometry
0,2,Av Icària - Àlaba,Barcelona,59,POINT (2.19898 41.3931)
2,2,Av Icària - Àlaba,Barcelona,H16,POINT (2.19898 41.3931)
3,2,Av Icària - Àlaba,Barcelona,V27,POINT (2.19898 41.3931)
4,3,València - Muntaner,Barcelona,63,POINT (2.15789 41.38855)
6,3,València - Muntaner,Barcelona,H10,POINT (2.15789 41.38855)
...,...,...,...,...,...
12998,201607,Av. Bertomeu - Pintor Fortuny,Cerdanyola del Vallès,CV2,POINT (2.08688 41.4973)
12999,201608,Av. Bertomeu - Pintor Fortuny,Cerdanyola del Vallès,CV2,POINT (2.08693 41.49737)
13000,201611,Les Forques,El Papiol,PA2,POINT (2.00512 41.43254)
13001,201612,Enric Granados - Narcís Monturiol,El Papiol,PA2,POINT (2.00701 41.43067)
13002,201613,Polígon Industrial,El Papiol,PA2,POINT (2.01052 41.43122)

In [37]:
correct_point_110024 = Point(2.144958892110339,41.34030702538247)

In [38]:
geo_df_stops_amb.loc[geo_df_stops_amb['code'] == 110024, 'geometry'] = correct_point_110024

In [39]:
geo_df_stops_amb[geo_df_stops_amb['code'] == 110024]

,code,name,municipi,lines,geometry
11571,110024,Tram VI - Edifici TERSACO,Barcelona,88,POINT (2.14496 41.34031)
11572,110024,Tram VI - Edifici TERSACO,Barcelona,89,POINT (2.14496 41.34031)

In [40]:
linies_w_trajectory = geo_df_traj_amb["linia"].unique().tolist()

In [41]:
geo_df_stops_amb = geo_df_stops_amb[geo_df_stops_amb["lines"].isin(linies_w_trajectory)]

In [42]:
geo_df_stops_amb[geo_df_stops_amb['lines'] == 'L86']

Empty GeoDataFrame
Columns: [code, name, municipi, lines, geometry]
Index: []

In [43]:
geo_df_stops_amb['lines'].nunique(), geo_df_stops_amb['code'].nunique()

(124, 3228)

In [44]:
geo_df_stops_amb['stop_type'] = 'Bus'
geo_df_stops_amb.rename(columns={"code": "stop_id", "name": "name", "lines": "linia"}, inplace=True)
geo_df_stops_amb = geo_df_stops_amb[['stop_id', 'name', 'linia', 'stop_type', 'geometry','municipi']]

# Solutinons

In [45]:
not_main_lines = ['133','113','115','175','112','119','185','136','109','124','131','123','196','126','120',
                  '114','132','141','116','130','157','117','182','191','104','121','102','107','122',
                  '129','111','127','180','115','183','118','128','199','125','JM']

not_main_lines2 = []

In [46]:
sols = geo_df_stops_amb.copy()
sols = sols[sols['municipi'] == 'Barcelona']
sols = sols[~sols['linia'].isin(not_main_lines)]
line_count = sols.groupby('stop_id').size().reset_index(name='counts').sort_values(by='counts', ascending=True)
line_count = pd.DataFrame(line_count)
stops_1_line = line_count[line_count['counts'] == 1]
sols = sols[~sols['stop_id'].isin(stops_1_line['stop_id'])]
sols.drop(columns=['municipi'], inplace=True)
sols['linia'] = 'IU Stop'
sols.drop_duplicates(subset=['stop_id'], inplace=True)
sols['id'] = 'SB' + '-' + sols['stop_id'].astype(str)
sols = sols[['id', 'stop_id', 'name', 'linia', 'stop_type', 'geometry']]

In [47]:
line_count

      stop_id  counts
807      1479       1
1067     2325       1
1066     2324       1
1062     2315       1
1061     2311       1
...       ...     ...
446       822       7
286       492       7
135       237       7
598      1098       7
288       494       7

[1615 rows x 2 columns]

In [48]:
geo_df_stops_amb[geo_df_stops_amb['stop_id'] == 112642]

,stop_id,name,linia,stop_type,geometry,municipi
12194,112642,"Gran de Gràcia, 160",87,Bus,POINT (2.15294 41.40217),Barcelona

In [49]:
geo_df_stops_amb[geo_df_stops_amb['linia'].str.startswith('LH2')]

,stop_id,name,linia,stop_type,geometry,municipi
232,91,Av Granvia - Miguel Hernández,LH2,Bus,POINT (2.12021 41.35276),L'Hospitalet de Llobregat
4306,1611,Parc de Bellvitge,LH2,Bus,POINT (2.11226 41.34827),L'Hospitalet de Llobregat
4573,1725,Complex Esportiu Hospitalet Nord,LH2,Bus,POINT (2.10158 41.37649),L'Hospitalet de Llobregat
5533,2517,Institut Mercè Rodoreda,LH2,Bus,POINT (2.10408 41.35564),L'Hospitalet de Llobregat
6024,2968,Amadeu Torner,LH2,Bus,POINT (2.12385 41.3555),L'Hospitalet de Llobregat
...,...,...,...,...,...,...
12060,112377,Llobregat - Pujós,LH2,Bus,POINT (2.11929 41.37366),L'Hospitalet de Llobregat
12088,112416,Tanatori,LH2,Bus,POINT (2.11171 41.34212),L'Hospitalet de Llobregat
12157,112526,Collblanc - Sant Ramon Nonat,LH2,Bus,POINT (2.11753 41.37582),Barcelona
12174,112554,Trav. Industrial - Rambla Marina,LH2,Bus,POINT (2.10793 41.35351),L'Hospitalet de Llobregat
12176,112555,Ctra. del Mig - Av. Fabregada,LH2,Bus,POINT (2.10933 41.35662),L'Hospitalet de Llobregat

In [50]:
sols.to_csv("Nodes/Bus-Sol.csv", index=False)

# Nodes

In [51]:
geo_df_stops_amb[geo_df_stops_amb['linia'] == '102']

,stop_id,name,linia,stop_type,geometry,municipi
1017,365,Lletres - Dante Alighieri,102,Bus,POINT (2.15792 41.42794),Barcelona
1049,374,Ctra d'Horta - Pg de Valldaura,102,Bus,POINT (2.15356 41.43727),Barcelona
1141,411,Tajo - Metro Horta,102,Bus,POINT (2.16109 41.42952),Barcelona
1305,476,Rambla del Carmel,102,Bus,POINT (2.15831 41.42604),Barcelona
1777,669,Bucle Entrada Recinte Cementiri,102,Bus,POINT (2.15618 41.46623),Cerdanyola del Vallès
1778,670,Agrupació número 1·2 - Jardí del Repòs,102,Bus,POINT (2.15806 41.46053),Cerdanyola del Vallès
1780,671,Agrupacions números 8 i 14,102,Bus,POINT (2.16256 41.45842),Montcada i Reixac
1782,673,Agrupació número 12·13 - Fossar,102,Bus,POINT (2.16285 41.45929),Montcada i Reixac
1784,674,Agrupació número 14·15,102,Bus,POINT (2.16124 41.46004),Montcada i Reixac
1786,675,Agrupació número 15,102,Bus,POINT (2.15949 41.46062),Montcada i Reixac
1788,676,Agrupació número 16 entrada,102,Bus,POINT (2.15892 41.4623),Montcada i Reixac
1790,678,Agrupació número 16 sortida,102,Bus,POINT (2.15882 41.46233),Montcada i Reixac
1792,679,Agrupació número 15 - Columbaris,102,Bus,POINT (2.15803 41.46148),Montcada i Reixac
1794,680,Bucle Sortida Recinte Cementiri,102,Bus,POINT (2.15602 41.46616),Cerdanyola del Vallès
2588,972,Pl Botticelli,102,Bus,POINT (2.15315 41.43312),Barcelona
2786,1051,Jerez - Pl de la Ciutadella,102,Bus,POINT (2.15526 41.43135),Barcelona
3835,1428,Ctra d'Horta - Av Estatut de Catalunya,102,Bus,POINT (2.15349 41.43743),Barcelona
3838,1430,Pl de l'Estatut,102,Bus,POINT (2.15519 41.43079),Barcelona
4484,1695,Ctra d'Horta,102,Bus,POINT (2.15422 41.43897),Barcelona
4613,1743,Ctra Cementiri de Collserola - Coll de la Ventosa,102,Bus,POINT (2.15894 41.44992),Barcelona
4661,1758,Coll de La Ventosa,102,Bus,POINT (2.15913 41.45015),Barcelona
4662,1759,Ctra del Cementiri de Collserola - Recinte Hebreu,102,Bus,POINT (2.15503 41.45972),Cerdanyola del Vallès
4663,1760,Ctra Cementiri Collserola - Camí Vall de St Iscle,102,Bus,POINT (2.15482 41.45899),Cerdanyola del Vallès
4722,1779,Ctra d'Horta - Ronda de Dalt,102,Bus,POINT (2.15436 41.4396),Barcelona
4758,1801,Agrupació número 16·17,102,Bus,POINT (2.15927 41.46337),Montcada i Reixac
5000,1998,Ctra Cementiri Collserola - Residència Joan XXIII,102,Bus,POINT (2.15601 41.46516),Cerdanyola del Vallès
5001,1999,Residència Joan XXIII,102,Bus,POINT (2.15599 41.46496),Cerdanyola del Vallès
5191,2234,Llobregós - Pg Maragall,102,Bus,POINT (2.16327 41.42777),Barcelona
5196,2235,Llobregós - Torrent del Carmel,102,Bus,POINT (2.1603 41.42652),Barcelona
5677,2622,Camí de l'Església - Rembrandt,102,Bus,POINT (2.1534 41.43414),Barcelona
5864,2804,"Pl del Complex Funerari, direcció Recinte",102,Bus,POINT (2.15587 41.47002),Cerdanyola del Vallès
5865,2805,"Pl del Complex Funerari, direcció Barcelona",102,Bus,POINT (2.15602 41.47021),Cerdanyola del Vallès
5980,2955,Agrupacions números 5 i 6,102,Bus,POINT (2.15823 41.45896),Montcada i Reixac
5981,2956,Agrupacions números 3 i 4,102,Bus,POINT (2.15784 41.45675),Montcada i Reixac
5982,2957,Agrupació número 11,102,Bus,POINT (2.16039 41.45497),Montcada i Reixac
5983,2958,Agrupacions números 7 i 8,102,Bus,POINT (2.15855 41.45747),Montcada i Reixac
5984,2959,Agrupació número 8,102,Bus,POINT (2.15941 41.45893),Montcada i Reixac
5985,2960,Agrupacions números 8 i 9,102,Bus,POINT (2.16176 41.45793),Montcada i Reixac
5986,2961,Agrupació número 10,102,Bus,POINT (2.16063 41.45789),Montcada i Reixac
5987,2962,Agrupacions números 9 i 10,102,Bus,POINT (2.16231 41.45688),Montcada i Reixac
5988,2963,Agrupació número 9,102,Bus,POINT (2.1639 41.45755),Montcada i Reixac
6043,2974,Tanatori de la Vall d'Hebron,102,Bus,POINT (2.1548 41.44048),Barcelona
6626,3368,Av l'Estatut de Catalunya - Campoamor,102,Bus,POINT (2.15354 41.43512),Barcelona
7160,3698,Lisboa - Santa Joana d'Arc,102,Bus,POINT (2.15794 41.42926),Barcelona

In [52]:
nodes_bus = geo_df_stops_amb.copy()
nodes_bus.drop(columns=['municipi'], inplace=True)
nodes_bus['id'] = 'B' + '-' + nodes_bus['linia'] + '-' + nodes_bus['stop_id'].astype(str)
nodes_bus = nodes_bus[['id', 'stop_id', 'name', 'linia', 'stop_type', 'geometry']]
nodes_bus = nodes_bus[~nodes_bus['linia'].isin(['199','86','116','102'])]
nodes_bus

,id,stop_id,name,linia,stop_type,geometry
0,B-59-2,2,Av Icària - Àlaba,59,Bus,POINT (2.19898 41.3931)
2,B-H16-2,2,Av Icària - Àlaba,H16,Bus,POINT (2.19898 41.3931)
3,B-V27-2,2,Av Icària - Àlaba,V27,Bus,POINT (2.19898 41.3931)
4,B-63-3,3,València - Muntaner,63,Bus,POINT (2.15789 41.38855)
6,B-H10-3,3,València - Muntaner,H10,Bus,POINT (2.15789 41.38855)
...,...,...,...,...,...,...
12179,B-87-112571,112571,Madrazo - Lincoln,87,Bus,POINT (2.14914 41.40042)
12192,B-B20-112593,112593,Font de l'Alzina,B20,Bus,POINT (2.19808 41.45849)
12193,B-M27-112593,112593,Font de l'Alzina,M27,Bus,POINT (2.19808 41.45849)
12194,B-87-112642,112642,"Gran de Gràcia, 160",87,Bus,POINT (2.15294 41.40217)
12246,B-B81-112736,112736,Elcano - Roger de Llúria,B81,Bus,POINT (2.21334 41.44253)

In [53]:
nodes_bus.to_csv("Nodes/Bus.csv", index=False)