In [47]:
import pandas as pd
import geopandas as gpd
import json
from shapely.geometry import shape, Point
from shapely import wkt
import warnings
from shapely.ops import linemerge, unary_union

# filter all warnings
warnings.filterwarnings("ignore")

In [48]:
neigh = pd.read_csv("Data/Neigh/neigh.csv")

neigh["geometry"] = neigh["geom"].apply(wkt.loads)

neigh = gpd.GeoDataFrame(
    neigh,
    geometry="geometry",
    crs="EPSG:4326"
)
neigh = neigh[["name", "geometry"]]
neigh["geometry"] = neigh.buffer(0)

In [49]:
with open('data/Bus/AMB.json') as f:
    data = json.load(f)


stops_amb = []
traj_amb = []

for collection in data:
    for feature in collection["features"]:
        props = feature["properties"]
        geom = feature["geometry"]
        if geom["type"] == "Point":
            stops_amb.append({
                "code": props["COD_EMT"],
                "name": props["NOMBRE"],
                "geometry": shape(geom)
            })
        if geom["type"] != "Point":
            traj_amb.append({
                "linia": props["LINEA"],
                "sentit": props["SENTIDO"],
                "geometry": shape(geom)
            })

geo_df_stops_amb = gpd.GeoDataFrame(stops_amb,geometry="geometry", crs="EPSG:4326")
geo_df_traj_amb = gpd.GeoDataFrame(traj_amb, geometry="geometry", crs="EPSG:4326")



buffered = neigh.copy()
buffered.to_crs('EPSG:25831', inplace=True)
buffered["geometry"] = buffered.geometry.buffer(2500)
# geo_df_stops_amb.to_crs('EPSG:25831', inplace=True)
# geo_df_stops_amb = gpd.sjoin(
#     geo_df_stops_amb,
#     buffered[["geometry"]],
#     predicate="within",
#     how="inner",
# ).drop(columns="index_right")
# geo_df_stops_amb.to_crs('EPSG:4326', inplace=True)

geo_df_traj_amb = (geo_df_traj_amb.groupby("linia", as_index=False).agg(geometry=("geometry", lambda s: unary_union(list(s)))))

geo_df_traj_amb = gpd.GeoDataFrame(geo_df_traj_amb,geometry="geometry",crs="EPSG:4326")

boundary = buffered.union_all()
geo_df_traj_amb.to_crs('EPSG:25831', inplace=True)
geo_df_traj_amb["inside_ratio"] = (
    geo_df_traj_amb.geometry.intersection(boundary).length
    / geo_df_traj_amb.geometry.length
)

geo_df_traj_amb = geo_df_traj_amb[
    geo_df_traj_amb["inside_ratio"] >= 0.6   # keep lines with >=20% inside
]


geo_df_traj_amb.to_crs('EPSG:4326', inplace=True)
geo_df_traj_amb.drop_duplicates(subset=['linia'],inplace=True)
geo_df_stops_amb.drop_duplicates(subset=['code'],inplace=True)

In [50]:
geo_df_traj_amb

    linia                                           geometry  inside_ratio
0     102  MULTILINESTRING ((2.15927 41.46337, 2.15926 41...           1.0
1     104  MULTILINESTRING ((2.18325 41.43168, 2.18322 41...           1.0
2     107  MULTILINESTRING ((2.15829 41.35209, 2.15822 41...           1.0
3     109  MULTILINESTRING ((2.12876 41.33011, 2.12874 41...           1.0
4      11  MULTILINESTRING ((2.17644 41.44856, 2.17643 41...           1.0
..    ...                                                ...           ...
223   V33  MULTILINESTRING ((2.22096 41.41384, 2.22089 41...           1.0
224    V5  MULTILINESTRING ((2.11035 41.39377, 2.11028 41...           1.0
225    V7  MULTILINESTRING ((2.14857 41.37657, 2.14854 41...           1.0
226    V9  MULTILINESTRING ((2.12066 41.40545, 2.12066 41...           1.0
229    X1  MULTILINESTRING ((2.1853 41.4011, 2.1853 41.40...           1.0

[156 rows x 3 columns]

In [51]:
# delete all the zeros before the bus stop code
geo_df_stops_amb["code"] = geo_df_stops_amb["code"].apply(lambda x: x.lstrip("0")).astype(int)
geo_df_stops_amb

         code                         name                  geometry
0      105083   Pg. Maritim - Port Ginesta  POINT (1.93085 41.26248)
1      109141        Pg. Maritim - Uruguai  POINT (1.94473 41.26459)
2      106979      Joan Maragall - escales  POINT (1.94449 41.27091)
3      107017   Av. del Poal - Comte Guell  POINT (1.94613 41.27432)
4      201017                    Osona, 33  POINT (1.94221 41.40663)
...       ...                          ...                       ...
12836  110371           Industria - Ponent  POINT (2.24013 41.43871)
12840  110494                       Bufala  POINT (2.24146 41.45804)
12852  108835            Parc de la Bobila  POINT (2.24467 41.46023)
12888  106055                Can Puigcarbo  POINT (2.26386 41.48403)
12917  106037  La Virreina - Ciutat Comtal  POINT (2.27951 41.47576)

[4915 rows x 3 columns]

In [52]:
bus_stops_w_line = pd.read_excel("Data/Bus/all_lines.xlsx")
len(bus_stops_w_line[bus_stops_w_line['Código de parada / Codi de parada'] == 2275])

1

In [53]:
geo_df_stops_amb

         code                         name                  geometry
0      105083   Pg. Maritim - Port Ginesta  POINT (1.93085 41.26248)
1      109141        Pg. Maritim - Uruguai  POINT (1.94473 41.26459)
2      106979      Joan Maragall - escales  POINT (1.94449 41.27091)
3      107017   Av. del Poal - Comte Guell  POINT (1.94613 41.27432)
4      201017                    Osona, 33  POINT (1.94221 41.40663)
...       ...                          ...                       ...
12836  110371           Industria - Ponent  POINT (2.24013 41.43871)
12840  110494                       Bufala  POINT (2.24146 41.45804)
12852  108835            Parc de la Bobila  POINT (2.24467 41.46023)
12888  106055                Can Puigcarbo  POINT (2.26386 41.48403)
12917  106037  La Virreina - Ciutat Comtal  POINT (2.27951 41.47576)

[4915 rows x 3 columns]

In [54]:
geo_df_stops_amb[geo_df_stops_amb['name'].str.startswith("Major - Pl")]

     code                    name                  geometry
318  2275  Major - Pl Constitucio  POINT (2.05493 41.36687)

In [55]:
bus_stops_w_line = pd.read_excel("Data/Bus/all_lines.xlsx")
bus_stops_w_line.rename(columns={"Código de parada / Codi de parada": "code",'Municipio / Municipi': 'municipi','Líneas / Línies': 'lines','UTM X': 'utm_x','UTM Y': 'utm_y','Nombre / Nom':'name'}, inplace=True)
bus_stops_w_line["utm_x"] = pd.to_numeric(
    bus_stops_w_line["utm_x"].astype(str).str.replace(",", ".", regex=False),
    errors="coerce"
)

bus_stops_w_line["utm_y"] = pd.to_numeric(
    bus_stops_w_line["utm_y"].astype(str).str.replace(",", ".", regex=False),
    errors="coerce"
)

geo_df_stops_amb = gpd.GeoDataFrame(
    bus_stops_w_line,
    geometry=gpd.points_from_xy(bus_stops_w_line["utm_x"], bus_stops_w_line["utm_y"]),
    crs="EPSG:25831"
)
geo_df_stops_amb.drop(columns=["utm_x", "utm_y",'Mobiliario / Mobiliari','Adaptada'], inplace=True) 
geo_df_stops_amb.to_crs('EPSG:4326', inplace=True)
geo_df_stops_amb = geo_df_stops_amb[geo_df_stops_amb["lines"].notnull()]
geo_df_stops_amb["lines"] = geo_df_stops_amb["lines"].apply(lambda x: [line.strip() for line in x.split("-")])
geo_df_stops_amb = geo_df_stops_amb.explode("lines", ignore_index=True)
geo_df_stops_amb = geo_df_stops_amb[~geo_df_stops_amb["lines"].str.startswith("N")] # treure bus nits
geo_df_stops_amb = geo_df_stops_amb[geo_df_stops_amb["lines"].isin(['A1','A2','MB3','PR4','JT','135','198','197']) == False] # treure bus aeroport
geo_df_stops_amb['lines'].nunique(), geo_df_stops_amb['code'].nunique()
geo_df_stops_amb

,code,name,municipi,lines,geometry
0,2,Av Icària - Àlaba,Barcelona,59,POINT (2.19898 41.3931)
2,2,Av Icària - Àlaba,Barcelona,H16,POINT (2.19898 41.3931)
3,2,Av Icària - Àlaba,Barcelona,V27,POINT (2.19898 41.3931)
4,3,València - Muntaner,Barcelona,63,POINT (2.15789 41.38855)
6,3,València - Muntaner,Barcelona,H10,POINT (2.15789 41.38855)
...,...,...,...,...,...
12998,201607,Av. Bertomeu - Pintor Fortuny,Cerdanyola del Vallès,CV2,POINT (2.08688 41.4973)
12999,201608,Av. Bertomeu - Pintor Fortuny,Cerdanyola del Vallès,CV2,POINT (2.08693 41.49737)
13000,201611,Les Forques,El Papiol,PA2,POINT (2.00512 41.43254)
13001,201612,Enric Granados - Narcís Monturiol,El Papiol,PA2,POINT (2.00701 41.43067)
13002,201613,Polígon Industrial,El Papiol,PA2,POINT (2.01052 41.43122)

In [56]:
correct_point_110024 = Point(2.144958892110339,41.34030702538247)

In [57]:
geo_df_stops_amb.loc[geo_df_stops_amb['code'] == 110024, 'geometry'] = correct_point_110024

In [58]:
geo_df_stops_amb[geo_df_stops_amb['code'] == 110024]

,code,name,municipi,lines,geometry
11571,110024,Tram VI - Edifici TERSACO,Barcelona,88,POINT (2.14496 41.34031)
11572,110024,Tram VI - Edifici TERSACO,Barcelona,89,POINT (2.14496 41.34031)

In [59]:
linies_w_trajectory = geo_df_traj_amb["linia"].unique().tolist()
geo_df_traj_amb["linia"].nunique()

156

In [60]:
geo_df_stops_amb = geo_df_stops_amb[geo_df_stops_amb["lines"].isin(linies_w_trajectory)]

In [61]:
geo_df_stops_amb['lines'].nunique(), geo_df_stops_amb['code'].nunique()

(124, 3228)

In [62]:
geo_df_stops_amb['stop_type'] = 'Bus'
geo_df_stops_amb.rename(columns={"code": "stop_id", "name": "name", "lines": "linia"}, inplace=True)
geo_df_stops_amb = geo_df_stops_amb[['stop_id', 'name', 'linia', 'stop_type', 'geometry','municipi']]

In [63]:
geo_df_stops_amb[geo_df_stops_amb['linia'].str.startswith('E')]

,stop_id,name,linia,stop_type,geometry,municipi
1594,590,Can Clota,EP1,Bus,POINT (2.09286 41.37709),Esplugues de Llobregat
1600,592,Laureà Miró - Josep Campreciós,EP2,Bus,POINT (2.08665 41.37748),Esplugues de Llobregat
2707,1017,Laureà Miró - Nord,EP1,Bus,POINT (2.0822 41.37809),Esplugues de Llobregat
2708,1017,Laureà Miró - Nord,EP2,Bus,POINT (2.0822 41.37809),Esplugues de Llobregat
2743,1034,Laureà Miró - Primer de Maig,EP1,Bus,POINT (2.09217 41.37693),Esplugues de Llobregat
...,...,...,...,...,...,...
11990,112170,Rosella - Dr. Gimeno,EP2,Bus,POINT (2.08601 41.38535),Esplugues de Llobregat
12033,112328,Hospital Sant Joan de Déu,EP1,Bus,POINT (2.10092 41.3834),Esplugues de Llobregat
12034,112329,Av. Cornellà - Jacint Verdaguer,EP1,Bus,POINT (2.08594 41.37494),Esplugues de Llobregat
12035,112330,Enrique Tierno Galván - Lleialtat,EP1,Bus,POINT (2.09325 41.37386),Esplugues de Llobregat
12156,112525,Finestrelles - Joan Miró,EP1,Bus,POINT (2.10041 41.38475),Esplugues de Llobregat

In [64]:
geo_df_stops_amb['linia'].unique()

array(['59', 'H16', 'V27', '63', 'H10', 'H12', '52', '13', '150', 'V33',
       '60', 'H8', '133', '27', '47', 'D40', '7', '33', '67', '113', 'H6',
       'M14', '175', '22', '87', 'V17', 'V21', '112', '119', '185', '76',
       '19', 'B25', 'B20', '136', 'V25', 'X1', '6', '54', 'V19', '78',
       '34', '109', 'V3', 'H4', 'M19', 'V11', '24', 'V15', 'V13', 'V9',
       '39', 'B24', 'V23', 'D50', '124', '131', 'H2', '123', '196', 'B80',
       'B15', 'B18', '65', 'LH2', '68', 'V7', '96', 'V31', '126', '55',
       '91', '120', 'D20', '114', '132', '70', 'V5', '141', '116', 'B21',
       'B23', '130', '23', '157', '117', '182', '192', '191', 'H14', '62',
       '104', '121', 'M12', 'JM', 'V1', 'V29', 'L16', 'LH1', '125', '102',
       '86', '107', '122', '97', '129', '111', 'EP1', 'EP2', 'PR3', 'L22',
       '21', '88', '127', 'B14', '180', '115', '183', 'B82', 'M27', '118',
       '128', '199', 'B81'], dtype=object)

# Solutinons

In [ ]:
not_main_lines = ['133','113','175','112','119','185','136','109','124','131','123','196','126','120',
                  '114','132','141','116','130','157','117','182','191','104','121','102','107','122',
                  '129','111','127','180','183','118','128','199']

not_main_lines2 = []

In [66]:
sols = geo_df_stops_amb.copy()
sols = sols[sols['municipi'] == 'Barcelona']
sols = sols[~sols['linia'].isin(not_main_lines)]
sols.drop(columns=['municipi'], inplace=True)
sols['linia'] = 'IU Stop'
sols.drop_duplicates(subset=['stop_id'], inplace=True)
sols['id'] = 'SB' + '-' + sols['stop_id'].astype(str)
sols = sols[['id', 'stop_id', 'name', 'linia', 'stop_type', 'geometry']]

In [67]:
len(sols)

1631

In [68]:
sols.to_csv("Nodes/Bus-Sol.csv", index=False)

In [69]:
sols

,id,stop_id,name,linia,stop_type,geometry
0,SB-2,2,Av Icària - Àlaba,IU Stop,Bus,POINT (2.19898 41.3931)
4,SB-3,3,València - Muntaner,IU Stop,Bus,POINT (2.15789 41.38855)
7,SB-4,4,Mallorca - Balmes,IU Stop,Bus,POINT (2.15873 41.39102)
13,SB-7,7,Pl Universitat,IU Stop,Bus,POINT (2.16331 41.38591)
17,SB-8,8,Pl de Carles Buïgas,IU Stop,Bus,POINT (2.15012 41.37105)
...,...,...,...,...,...,...
12080,SB-112403,112403,Service Center,IU Stop,Bus,POINT (2.13635 41.32232)
12147,SB-112480,112480,Rda. Sant Pere - Pl. Urquinaona,IU Stop,Bus,POINT (2.17474 41.38979)
12157,SB-112526,112526,Collblanc - Sant Ramon Nonat,IU Stop,Bus,POINT (2.11753 41.37582)
12179,SB-112571,112571,Madrazo - Lincoln,IU Stop,Bus,POINT (2.14914 41.40042)
12194,SB-112642,112642,"Gran de Gràcia, 160",IU Stop,Bus,POINT (2.15294 41.40217)

# Nodes

In [70]:
nodes_bus = geo_df_stops_amb.copy()
nodes_bus.drop(columns=['municipi'], inplace=True)
nodes_bus['id'] = 'B' + '-' + nodes_bus['linia'] + '-' + nodes_bus['stop_id'].astype(str)
nodes_bus = nodes_bus[['id', 'stop_id', 'name', 'linia', 'stop_type', 'geometry']]

In [71]:
nodes_bus.to_csv("Nodes/Bus.csv", index=False)