In [2]:
import pandas as pd
import geopandas as gpd
import altair as alt
import json
from shapely.geometry import shape
from shapely import wkt
from shapely.ops import linemerge, substring, unary_union
alt.data_transformers.disable_max_rows()

DataTransformerRegistry.enable('default')

In [3]:
neigh = pd.read_csv("Data/Neigh/neigh.csv")

neigh["geometry"] = neigh["geom"].apply(wkt.loads)

neigh = gpd.GeoDataFrame(
    neigh,
    geometry="geometry",
    crs="EPSG:4326"
)
neigh = neigh[["name", "geometry"]]
neigh["geometry"] = neigh.buffer(0)

neigh_layer = alt.Chart(neigh).mark_geoshape(
    stroke="black",
    fill="lightblue"
).encode(tooltip=['name'])

In [ ]:
nodes = pd.read_csv("Nodes/BUS.csv")
nodes['geometry']= nodes['geometry'].apply(wkt.loads)
nodes = gpd.GeoDataFrame(nodes, geometry='geometry', crs="EPSG:4326")

3145

In [ ]:
with open('data/Bus/AMB2.json') as f:
    data = json.load(f)


traj_amb = []

for collection in data:
    for feature in collection["features"]:
        props = feature["properties"]
        geom = feature["geometry"]
        
        if geom["type"] != "Point":
            traj_amb.append({
                "linia": props["LINEA"],
                "sentit": props["SENTIDO"],
                "geometry": shape(geom)
            })

geo_df_traj_amb = gpd.GeoDataFrame(traj_amb, geometry="geometry", crs="EPSG:4326")
#geo_df_traj_amb = (geo_df_traj_amb.groupby("linia", as_index=False).agg(geometry=("geometry", lambda s: unary_union(list(s)))))

geo_df_traj_amb = gpd.GeoDataFrame(geo_df_traj_amb,geometry="geometry",crs="EPSG:4326")

buffered = neigh.copy()
buffered.to_crs('EPSG:25831', inplace=True)
buffered["geometry"] = buffered.geometry.buffer(2500)
boundary = buffered.union_all()
geo_df_traj_amb.to_crs('EPSG:25831', inplace=True)
geo_df_traj_amb["inside_ratio"] = (
    geo_df_traj_amb.geometry.intersection(boundary).length
    / geo_df_traj_amb.geometry.length
)

geo_df_traj_amb = geo_df_traj_amb[
    geo_df_traj_amb["inside_ratio"] >= 0.60   # keep lines with >=20% inside
]


geo_df_traj_amb.to_crs('EPSG:4326', inplace=True)
geo_df_traj_amb.sort_values(by='inside_ratio', inplace=True)
geo_df_traj_amb = geo_df_traj_amb[geo_df_traj_amb['linia'].isin(nodes['linia'].unique())]
geo_df_traj_amb.sort_values(by='inside_ratio', inplace=True)
geo_df_traj_amb

In [ ]:
nodes[nodes['stop_id'] == 2275]

In [ ]:
geo_df_traj_amb[geo_df_traj_amb['linia'] == '78']

In [ ]:
lines = alt.Chart(geo_df_traj_amb[geo_df_traj_amb['linia'] == '78']).mark_geoshape(
    filled=False, 
    strokeWidth=4
).encode(
    color=alt.Color('tram:N', legend=alt.Legend(title="Metro Segments")),
    tooltip=['tram:N']
)

points = alt.Chart(nodes[nodes['linia'] == '78']).mark_geoshape(size=0, color='red').encode(tooltip=['name:N'])
plot = (lines + points).project('mercator').properties(width=800, height=600)
plot

In [ ]:
nodes[nodes['linia'] == '78'].sort_values(by='stop_id')

In [ ]:
def break_trajectory(trajectory_df, stops):

    line = trajectory_df.geometry.iloc[0]
    #line = trajectory_df[trajectory_df['route_id'] == 'L6'].geometry.iloc[0]

    flattened_line = unary_union(line) 
    merged_line = linemerge(flattened_line)

    if merged_line.geom_type == 'MultiLineString':
        line_s = max(merged_line.geoms, key=lambda x: x.length)
    else:
        line_s = merged_line

    stop_list = []
    for _, row in stops.iterrows():
        dist = line_s.project(row.geometry)
        stop_list.append({'name': row['name'], 'id': row['id'], 'dist': dist})
    sorted_stops = sorted(stop_list, key=lambda x: x['dist'])

    # 4. Create segments
    segments_data = []
    for i in range(len(sorted_stops) - 1):
        origin = sorted_stops[i]
        destination = sorted_stops[i+1]
        
        # Check for zero length (stops at the same location)
        if abs(destination['dist'] - origin['dist']) < 1e-7:
            print(f"Skipping zero-length segment between {origin['name']} and {destination['name']}")
            continue
            
        seg_geom = substring(line_s, origin['dist'], destination['dist'])
        
        segments_data.append({
            'origen': origin['id'],
            'dest': destination['id'],
            'tram': f"{origin['name']} - {destination['name']}",
            'linia': trajectory_df['linia'].iloc[0],
            'type' : 'Bus',
            'geometry': seg_geom,
        })

    print(f"Generated segments: {len(segments_data)}")

    segments_gdf = gpd.GeoDataFrame(segments_data, crs="EPSG:4326",geometry='geometry')

    return segments_gdf

In [ ]:
geo_df_traj_amb[geo_df_traj_amb['linia'] == '78']

In [ ]:
nodes[nodes['linia'] == '78']

In [117]:
b78 = nodes[nodes['linia'] == '78']
b78[b78['name'].str.contains('Major - Pl')]

,id,stop_id,name,linia,stop_type,geometry
13,B-78-2275,2275,Major - Pl Constitucio,78,Bus,POINT (2.05493 41.36687)

In [118]:
bus_edges = pd.DataFrame()
for route in geo_df_traj_amb['linia'].unique():
    print(f"Processing route: {route}")

    segments_gdf = break_trajectory(geo_df_traj_amb[(geo_df_traj_amb['linia'] == route) & (geo_df_traj_amb['sentit'] == 'Sentido Pl dels Paisos Catalans')], nodes[nodes['linia'] == route])
    bus_edges = pd.concat([bus_edges, segments_gdf], ignore_index=True)
bus_edges

Processing route: PR3
Processing route: 78
[{'name': 'Ctra BV 2001- Benzinera', 'id': 'B-78-3433', 'dist': 0.0}, {'name': 'Ctra BV 2001- Benzinera', 'id': 'B-78-3429', 'dist': 0.0}, {'name': "Major - Riera d'en Nofre", 'id': 'B-78-3428', 'dist': 0.0}, {'name': "Rambla Josep M Jujol - Baltasar d'Espanya", 'id': 'B-78-2274', 'dist': 0.0}, {'name': 'Major - Pl Constitucio', 'id': 'B-78-2275', 'dist': 0.0}, {'name': 'Major - Montjuic', 'id': 'B-78-2276', 'dist': 0.0}, {'name': 'Av Barcelona - Major', 'id': 'B-78-2667', 'dist': 0.0}, {'name': 'Av Barcelona - Rius i Taulet', 'id': 'B-78-2248', 'dist': 0.0}, {'name': 'Av Barcelona - Tambor del Bruc', 'id': 'B-78-904', 'dist': 0.0}, {'name': 'Fructuos Gelabert - Jacint Verdaguer', 'id': 'B-78-1739', 'dist': 0.0}, {'name': 'Av Barcelona - Mare de Deu de la Merce', 'id': 'B-78-1657', 'dist': 0.0}, {'name': 'Jacint Verdaguer  -  Josep Trueta', 'id': 'B-78-3135', 'dist': 0.0}, {'name': 'Jacint Verdaguer - de la TV3', 'id': 'B-78-1633', 'dist': 0.0}, {'name': "Av Baix Llobregat - St Marti de l'Erm", 'id': 'B-78-1919', 'dist': 0.0}, {'name': 'Av Baix Llobregat - Angel Guimera', 'id': 'B-78-2636', 'dist': 0.0}, {'name': 'Av Baix Llobregat - Enric Granados', 'id': 'B-78-2638', 'dist': 0.0}, {'name': 'Av de Cornella - Gall', 'id': 'B-78-645', 'dist': 0.0}, {'name': 'Av de Cornella - Mila i Pi', 'id': 'B-78-644', 'dist': 0.0}, {'name': "Major - Creu d'en Muntaner", 'id': 'B-78-3434', 'dist': 0.0}, {'name': 'Rambla Josep M Jujol - Montjuic', 'id': 'B-78-2273', 'dist': 0.0}, {'name': 'Av Barcelona - Bon Viatge', 'id': 'B-78-2271', 'dist': 0.0}, {'name': 'Av Barcelona - Francesc Macia', 'id': 'B-78-1102', 'dist': 0.0}, {'name': 'Av Barcelona - Poliesportiu Municipal', 'id': 'B-78-1737', 'dist': 0.0}, {'name': 'Av Barcelona - Gran Capita', 'id': 'B-78-537', 'dist': 0.0}, {'name': 'Av Barcelona - Mare de Deu de Montserrat', 'id': 'B-78-536', 'dist': 0.0}, {'name': "Fructuos Gelabert - Sant Marti de l'Erm", 'id': 'B-78-632', 'dist': 0.0}, {'name': 'Jacint Verdaguer - Estudis TV3', 'id': 'B-78-470', 'dist': 0.0}, {'name': 'Av Barcelona - Marques de Monistrol', 'id': 'B-78-276', 'dist': 0.0}, {'name': "St Marti de l'Erm - Zona Esportiva Fontsanta", 'id': 'B-78-1658', 'dist': 0.0}, {'name': 'Jacint Verdaguer - Fructuos Gelabert', 'id': 'B-78-1486', 'dist': 0.0}, {'name': 'Av Baix Llobregat - Jacint Verdaguer', 'id': 'B-78-3136', 'dist': 0.0}, {'name': 'Ctra BV 2001- Onze de Setembre', 'id': 'B-78-3432', 'dist': 0.0}, {'name': "Rambla Josep M Jujol - Riera d'en Nofre", 'id': 'B-78-2247', 'dist': 0.0}, {'name': 'Av Baix Llobregat - Av Barcelona', 'id': 'B-78-2635', 'dist': 0.0}, {'name': 'Av Baix Llobregat - Cirerers', 'id': 'B-78-2637', 'dist': 0.0}, {'name': 'Av de Cornella - Montesa', 'id': 'B-78-151', 'dist': 0.0}, {'name': 'Ctra BV 2001- Onze de Setembre', 'id': 'B-78-3430', 'dist': 0.0}, {'name': 'Onze de Setembre - Pg  del Canal', 'id': 'B-78-3431', 'dist': 0.0}, {'name': "St Marti de l'Erm - Zona Esportiva Fontsanta", 'id': 'B-78-1485', 'dist': 0.0}, {'name': 'Av de Cornella - Pl Sardana', 'id': 'B-78-748', 'dist': 8.386300670063036e-06}, {'name': 'Av de Cornella - St Francesc Xavier', 'id': 'B-78-1411', 'dist': 0.0013979481734023712}, {'name': 'Av de Cornella - 8 de Marc', 'id': 'B-78-1460', 'dist': 0.003220177784045922}, {'name': "Av de Cornella - Pont d'Esplugues", 'id': 'B-78-1461', 'dist': 0.006607441765169945}, {'name': 'Av dels Paisos Catalans - Laurea Miro', 'id': 'B-78-1459', 'dist': 0.010066038999450059}, {'name': 'Av dels Paisos Catalans - Laurea Miro', 'id': 'B-78-1746', 'dist': 0.010603124381871073}, {'name': 'Av dels Paisos Catalans - David Carreras i Trias', 'id': 'B-78-1458', 'dist': 0.013751104282526036}, {'name': "Av dels Paisos Catalans - Direccio Gral d'Esports", 'id': 'B-78-1747', 'dist': 0.014181329399750451}, {'name': 'Juan de la Cierva - Av Jacint Esteva Fontanet', 'id': 'B-78-3751', 'dist': 0.01754135784463483}, {'name': "Av d'Ahrensburg - Av Jacint Esteva Fontanet", 'id': 'B-78-3725', 'dist': 0.018099416227604363}, {'name': 'Juan de la Cierva - Pau Casals', 'id': 'B-78-3752', 'dist': 0.020377783590572615}, {'name': 'Hospital Sant Joan de Deu', 'id': 'B-78-3753', 'dist': 0.021769120823927793}, {'name': 'Hospital Sant Joan de Deu', 'id': 'B-78-3724', 'dist': 0.02202487815657984}, {'name': 'Parc de Cervantes', 'id': 'B-78-1881', 'dist': 0.025953189328202373}, {'name': "Av d'Esplugues - Gonzalez Tablas", 'id': 'B-78-761', 'dist': 0.028921219311474355}, {'name': "Av d'Esplugues - Eduard Toldra", 'id': 'B-78-552', 'dist': 0.029200708041732516}, {'name': "Av d'Esplugues - Dr Joaquim Albarran", 'id': 'B-78-550', 'dist': 0.03237883192966804}, {'name': "Av d'Esplugues", 'id': 'B-78-762', 'dist': 0.03244531439296161}, {'name': "Av d'Esplugues - Av Pearson", 'id': 'B-78-549', 'dist': 0.03596178015816823}, {'name': "Av d'Esplugues - Av Pearson", 'id': 'B-78-763', 'dist': 0.037202222708775046}, {'name': 'Av. Pedralbes - Cavallers', 'id': 'B-78-172', 'dist': 0.04152727995508218}, {'name': 'Av Pedralbes - Cavallers', 'id': 'B-78-711', 'dist': 0.04152727995508218}, {'name': 'Av Pedralbes - Pg  Manuel Girona', 'id': 'B-78-297', 'dist': 0.04630793747447498}, {'name': 'Av Pedralbes - Toquio', 'id': 'B-78-1413', 'dist': 0.04630793747447498}, {'name': 'Pl Pius XII', 'id': 'B-78-765', 'dist': 0.04960003369251111}, {'name': 'Diagonal - Av Joan XXIII', 'id': 'B-78-492', 'dist': 0.05203523819668997}, {'name': 'Diagonal - Gran Via Carles III', 'id': 'B-78-493', 'dist': 0.0547444167809995}, {'name': 'Diagonal - Pl Reina Maria Cristina', 'id': 'B-78-237', 'dist': 0.05671743978536316}, {'name': 'Diagonal - Gandesa', 'id': 'B-78-494', 'dist': 0.05822257652976995}, {'name': 'Diagonal - Numancia', 'id': 'B-78-483', 'dist': 0.06114924598845218}, {'name': 'Numancia - Diagonal', 'id': 'B-78-1380', 'dist': 0.06240994259854361}, {'name': 'Diagonal - Doctor Fleming', 'id': 'B-78-41', 'dist': 0.06375914330877495}, {'name': 'Numancia - Parc Les Corts', 'id': 'B-78-990', 'dist': 0.06670192731467926}, {'name': 'Entenca - Montnegre', 'id': 'B-78-1381', 'dist': 0.06762765761554074}, {'name': 'Nicaragua - Parc Les Corts', 'id': 'B-78-1377', 'dist': 0.06800447658429672}, {'name': 'Numancia - Marques de Sentmenat', 'id': 'B-78-109', 'dist': 0.06893727610081661}, {'name': 'Numancia - Berlin', 'id': 'B-78-629', 'dist': 0.07168145188983248}, {'name': 'Nicaragua - Josep Tarradellas', 'id': 'B-78-110', 'dist': 0.07347370731557108}, {'name': 'Numancia - Av Roma', 'id': 'B-78-2270', 'dist': 0.07415688617035321}, {'name': 'Av Roma - Tarragona', 'id': 'B-78-777', 'dist': 0.07891604775054516}]
Skipping zero-length segment between Ctra BV 2001- Benzinera and Ctra BV 2001- Benzinera
Skipping zero-length segment between Ctra BV 2001- Benzinera and Major - Riera d'en Nofre
Skipping zero-length segment between Major - Riera d'en Nofre and Rambla Josep M Jujol - Baltasar d'Espanya
Skipping zero-length segment between Rambla Josep M Jujol - Baltasar d'Espanya and Major - Pl Constitucio
Skipping zero-length segment between Major - Pl Constitucio and Major - Montjuic
Skipping zero-length segment between Major - Montjuic and Av Barcelona - Major
Skipping zero-length segment between Av Barcelona - Major and Av Barcelona - Rius i Taulet
Skipping zero-length segment between Av Barcelona - Rius i Taulet and Av Barcelona - Tambor del Bruc
Skipping zero-length segment between Av Barcelona - Tambor del Bruc and Fructuos Gelabert - Jacint Verdaguer
Skipping zero-length segment between Fructuos Gelabert - Jacint Verdaguer and Av Barcelona - Mare de Deu de la Merce
Skipping zero-length segment between Av Barcelona - Mare de Deu de la Merce and Jacint Verdaguer  -  Josep Trueta
Skipping zero-length segment between Jacint Verdaguer  -  Josep Trueta and Jacint Verdaguer - de la TV3
Skipping zero-length segment between Jacint Verdaguer - de la TV3 and Av Baix Llobregat - St Marti de l'Erm
Skipping zero-length segment between Av Baix Llobregat - St Marti de l'Erm and Av Baix Llobregat - Angel Guimera
Skipping zero-length segment between Av Baix Llobregat - Angel Guimera and Av Baix Llobregat - Enric Granados
Skipping zero-length segment between Av Baix Llobregat - Enric Granados and Av de Cornella - Gall
Skipping zero-length segment between Av de Cornella - Gall and Av de Cornella - Mila i Pi
Skipping zero-length segment between Av de Cornella - Mila i Pi and Major - Creu d'en Muntaner
Skipping zero-length segment between Major - Creu d'en Muntaner and Rambla Josep M Jujol - Montjuic
Skipping zero-length segment between Rambla Josep M Jujol - Montjuic and Av Barcelona - Bon Viatge
Skipping zero-length segment between Av Barcelona - Bon Viatge and Av Barcelona - Francesc Macia
Skipping zero-length segment between Av Barcelona - Francesc Macia and Av Barcelona - Poliesportiu Municipal
Skipping zero-length segment between Av Barcelona - Poliesportiu Municipal and Av Barcelona - Gran Capita
Skipping zero-length segment between Av Barcelona - Gran Capita and Av Barcelona - Mare de Deu de Montserrat
Skipping zero-length segment between Av Barcelona - Mare de Deu de Montserrat and Fructuos Gelabert - Sant Marti de l'Erm
Skipping zero-length segment between Fructuos Gelabert - Sant Marti de l'Erm and Jacint Verdaguer - Estudis TV3
Skipping zero-length segment between Jacint Verdaguer - Estudis TV3 and Av Barcelona - Marques de Monistrol
Skipping zero-length segment between Av Barcelona - Marques de Monistrol and St Marti de l'Erm - Zona Esportiva Fontsanta
Skipping zero-length segment between St Marti de l'Erm - Zona Esportiva Fontsanta and Jacint Verdaguer - Fructuos Gelabert
Skipping zero-length segment between Jacint Verdaguer - Fructuos Gelabert and Av Baix Llobregat - Jacint Verdaguer
Skipping zero-length segment between Av Baix Llobregat - Jacint Verdaguer and Ctra BV 2001- Onze de Setembre
Skipping zero-length segment between Ctra BV 2001- Onze de Setembre and Rambla Josep M Jujol - Riera d'en Nofre
Skipping zero-length segment between Rambla Josep M Jujol - Riera d'en Nofre and Av Baix Llobregat - Av Barcelona
Skipping zero-length segment between Av Baix Llobregat - Av Barcelona and Av Baix Llobregat - Cirerers
Skipping zero-length segment between Av Baix Llobregat - Cirerers and Av de Cornella - Montesa
Skipping zero-length segment between Av de Cornella - Montesa and Ctra BV 2001- Onze de Setembre
Skipping zero-length segment between Ctra BV 2001- Onze de Setembre and Onze de Setembre - Pg  del Canal
Skipping zero-length segment between Onze de Setembre - Pg  del Canal and St Marti de l'Erm - Zona Esportiva Fontsanta
Skipping zero-length segment between Av. Pedralbes - Cavallers and Av Pedralbes - Cavallers
Skipping zero-length segment between Av Pedralbes - Pg  Manuel Girona and Av Pedralbes - Toquio
Generated segments: 38
Processing route: B24
Processing route: 157
Processing route: M19
Processing route: MB3
Processing route: 68
Processing route: B25
Processing route: A2
Processing route: 67
Processing route: M27
Processing route: 96
Processing route: 65
Processing route: JT
Processing route: 63
Processing route: V33
Processing route: 136
Processing route: M12
Processing route: 22
Processing route: 24
Processing route: 34
Processing route: V31
Processing route: V15
Processing route: 7
Processing route: 76
Processing route: 62
Processing route: 27
Processing route: JM
Processing route: 88
Processing route: PR4
Processing route: B23
Processing route: 116
Processing route: 150
Processing route: 102
Processing route: 47
Processing route: H4
Processing route: H16
Processing route: H14
Processing route: 54
Processing route: 122
Processing route: 60
Processing route: 91
Processing route: 183
Processing route: V21
Processing route: L16
Processing route: 124
Processing route: 120
Processing route: V3
Processing route: 131
Processing route: 107
Processing route: H6
Processing route: 52
Processing route: 128
Processing route: D50
Processing route: 55
Processing route: 114
Processing route: 185
Processing route: 126
Processing route: L22
Processing route: B20
Processing route: 97
Processing route: 133
Processing route: X1
Processing route: 119
Processing route: 13
Processing route: 19
Processing route: 115
Processing route: B14
Processing route: 112
Processing route: B80
Processing route: 33
Processing route: 70
Processing route: 132
Processing route: 198
Processing route: 23
Processing route: 6
Processing route: 121
Processing route: V1
Processing route: 129
Processing route: D20
Processing route: EP2
Processing route: 59
Processing route: V13
Processing route: V25
Processing route: V27
Processing route: V11
Processing route: 127
Processing route: 111
Processing route: 141
Processing route: 123
Processing route: D40
Processing route: M14
Processing route: 182
Processing route: 175
Processing route: V9
Processing route: V5
Processing route: V17
Processing route: 39
Processing route: B81
Processing route: B21
Processing route: 192
Processing route: 109
Processing route: 130
Processing route: V29
Processing route: 196
Processing route: 87
Processing route: 191
Processing route: EP1
Processing route: H8
Processing route: B15
Processing route: V23
Processing route: V19
Processing route: 113
Processing route: 125
Processing route: B18
Processing route: 104
Processing route: 86
Processing route: B82
Processing route: V7
Processing route: 197
Processing route: 21
Processing route: 118
Processing route: 117
Processing route: LH2
Processing route: H2
Processing route: H12
Processing route: H10
Processing route: 180
Processing route: 199
Processing route: 135
Processing route: LH1

,origen,dest,tram,linia,type,geometry
0,B-78-1485,B-78-748,St Marti de l'Erm - Zona Esportiva Fontsanta -...,78,Bus,"LINESTRING (2.08393 41.37254, 2.08393 41.37254)"
1,B-78-748,B-78-1411,Av de Cornella - Pl Sardana - Av de Cornella -...,78,Bus,"LINESTRING (2.08393 41.37254, 2.0849 41.37354)"
2,B-78-1411,B-78-1460,Av de Cornella - St Francesc Xavier - Av de Co...,78,Bus,"LINESTRING (2.0849 41.37354, 2.08612 41.3748, ..."
3,B-78-1460,B-78-1461,Av de Cornella - 8 de Marc - Av de Cornella - ...,78,Bus,"LINESTRING (2.08618 41.37484, 2.08618 41.37484..."
4,B-78-1461,B-78-1459,Av de Cornella - Pont d'Esplugues - Av dels Pa...,78,Bus,"LINESTRING (2.08886 41.37683, 2.08886 41.37683..."
5,B-78-1459,B-78-1746,Av dels Paisos Catalans - Laurea Miro - Av del...,78,Bus,"LINESTRING (2.09148 41.37749, 2.09182 41.37778..."
6,B-78-1746,B-78-1458,Av dels Paisos Catalans - Laurea Miro - Av del...,78,Bus,"LINESTRING (2.09189 41.37783, 2.09189 41.37783..."
7,B-78-1458,B-78-1747,Av dels Paisos Catalans - David Carreras i Tri...,78,Bus,"LINESTRING (2.0946 41.37943, 2.0949 41.37961, ..."
8,B-78-1747,B-78-3751,Av dels Paisos Catalans - Direccio Gral d'Espo...,78,Bus,"LINESTRING (2.09496 41.37965, 2.09751 41.38184)"
9,B-78-3751,B-78-3725,Juan de la Cierva - Av Jacint Esteva Fontanet ...,78,Bus,"LINESTRING (2.09751 41.38184, 2.09794 41.38221)"
10,B-78-3725,B-78-3752,Av d'Ahrensburg - Av Jacint Esteva Fontanet - ...,78,Bus,"LINESTRING (2.09794 41.38221, 2.09794 41.38218..."
11,B-78-3752,B-78-3753,Juan de la Cierva - Pau Casals - Hospital Sant...,78,Bus,"LINESTRING (2.10011 41.38277, 2.10024 41.38283..."
12,B-78-3753,B-78-3724,Hospital Sant Joan de Deu - Hospital Sant Joan...,78,Bus,"LINESTRING (2.10125 41.38352, 2.10143 41.38355..."
13,B-78-3724,B-78-1881,Hospital Sant Joan de Deu - Parc de Cervantes,78,Bus,"LINESTRING (2.1015 41.38357, 2.1015 41.38357, ..."
14,B-78-1881,B-78-761,Parc de Cervantes - Av d'Esplugues - Gonzalez ...,78,Bus,"LINESTRING (2.10471 41.38528, 2.10471 41.38528..."
15,B-78-761,B-78-552,Av d'Esplugues - Gonzalez Tablas - Av d'Esplug...,78,Bus,"LINESTRING (2.10666 41.38748, 2.10666 41.38748..."
16,B-78-552,B-78-550,Av d'Esplugues - Eduard Toldra - Av d'Esplugue...,78,Bus,"LINESTRING (2.1068 41.38768, 2.10812 41.38914,..."
17,B-78-550,B-78-762,Av d'Esplugues - Dr Joaquim Albarran - Av d'Es...,78,Bus,"LINESTRING (2.10909 41.38986, 2.10915 41.3899,..."
18,B-78-762,B-78-549,Av d'Esplugues - Av d'Esplugues - Av Pearson,78,Bus,"LINESTRING (2.10915 41.3899, 2.10915 41.38989,..."
19,B-78-549,B-78-763,Av d'Esplugues - Av Pearson - Av d'Esplugues -...,78,Bus,"LINESTRING (2.11172 41.39212, 2.11195 41.39323..."
20,B-78-763,B-78-172,Av d'Esplugues - Av Pearson - Av. Pedralbes - ...,78,Bus,"LINESTRING (2.112 41.39332, 2.112 41.39332, 2...."
21,B-78-711,B-78-297,Av Pedralbes - Cavallers - Av Pedralbes - Pg ...,78,Bus,"LINESTRING (2.11519 41.3929, 2.11519 41.39286,..."
22,B-78-1413,B-78-765,Av Pedralbes - Toquio - Pl Pius XII,78,Bus,"LINESTRING (2.11894 41.39, 2.11894 41.38995, 2..."
23,B-78-765,B-78-492,Pl Pius XII - Diagonal - Av Joan XXIII,78,Bus,"LINESTRING (2.12151 41.38798, 2.12201 41.3876,..."
24,B-78-492,B-78-493,Diagonal - Av Joan XXIII - Diagonal - Gran Via...,78,Bus,"LINESTRING (2.12299 41.38693, 2.12298 41.38691..."
25,B-78-493,B-78-237,Diagonal - Gran Via Carles III - Diagonal - Pl...,78,Bus,"LINESTRING (2.12558 41.38759, 2.12558 41.38758..."
26,B-78-237,B-78-494,Diagonal - Pl Reina Maria Cristina - Diagonal ...,78,Bus,"LINESTRING (2.12748 41.38806, 2.12886 41.3884,..."
27,B-78-494,B-78-483,Diagonal - Gandesa - Diagonal - Numancia,78,Bus,"LINESTRING (2.12893 41.38844, 2.12892 41.3884,..."
28,B-78-483,B-78-1380,Diagonal - Numancia - Numancia - Diagonal,78,Bus,"LINESTRING (2.13172 41.38912, 2.13262 41.38936..."
29,B-78-1380,B-78-41,Numancia - Diagonal - Diagonal - Doctor Fleming,78,Bus,"LINESTRING (2.13286 41.38915, 2.13286 41.38915..."
30,B-78-41,B-78-990,Diagonal - Doctor Fleming - Numancia - Parc Le...,78,Bus,"LINESTRING (2.13378 41.38818, 2.13581 41.38614..."
31,B-78-990,B-78-1381,Numancia - Parc Les Corts - Entenca - Montnegre,78,Bus,"LINESTRING (2.13587 41.38614, 2.13587 41.38614..."
32,B-78-1381,B-78-1377,Entenca - Montnegre - Nicaragua - Parc Les Corts,78,Bus,"LINESTRING (2.1365 41.38548, 2.13677 41.38522)"
33,B-78-1377,B-78-109,Nicaragua - Parc Les Corts - Numancia - Marque...,78,Bus,"LINESTRING (2.13677 41.38522, 2.13739 41.38461..."
34,B-78-109,B-78-629,Numancia - Marques de Sentmenat - Numancia - B...,78,Bus,"LINESTRING (2.13746 41.38461, 2.13746 41.38457..."
35,B-78-629,B-78-110,Numancia - Berlin - Nicaragua - Josep Tarradellas,78,Bus,"LINESTRING (2.13945 41.38276, 2.13945 41.38276..."
36,B-78-110,B-78-2270,Nicaragua - Josep Tarradellas - Numancia - Av ...,78,Bus,"LINESTRING (2.1408 41.3816, 2.1413 41.38121, 2..."
37,B-78-2270,B-78-777,Numancia - Av Roma - Av Roma - Tarragona,78,Bus,"LINESTRING (2.14134 41.38121, 2.14135 41.38117..."

In [105]:
lines = alt.Chart(bus_edges[bus_edges['linia'] == '78']).mark_geoshape(
    filled=False, 
    strokeWidth=4
).encode(
    color=alt.Color('tram:N', legend=alt.Legend(title="Metro Segments")),
    tooltip=['tram:N']
)

points = alt.Chart(nodes[nodes['linia'] == '78']).mark_geoshape(size=0, color='red').encode(tooltip=['name:N'])
plot = (lines + points).project('mercator').properties(width=800, height=600).interactive()
plot

alt.LayerChart(...)