In [98]:
import pandas as pd
import json
import geopandas as gpd
import altair as alt

from shapely.geometry import LineString
from shapely.geometry import shape
from shapely import wkt

alt.data_transformers.enable("vegafusion")

DataTransformerRegistry.enable('vegafusion')

In [99]:
alt.data_transformers.enable("vegafusion", max_rows=None)

path = "mataro/mapa-municipal-v2r0-mataro-municipi-20240118.shp"
gdf2 = gpd.read_file(path)
gdf2.to_crs(4326,inplace=True)
alt.Chart(gdf2).mark_geoshape(size = 0,filled = False)

alt.Chart(...)

# E11.2

In [100]:
maxidecor = shape({
    'type': 'Point',
    'coordinates': ( 2.432855639688924, 41.55125826729664)
})

mistral = shape({
    'type': 'Point',
    'coordinates': (2.438210539688879, 41.5492735576043)
})


figuera_major = shape({
    'type': 'Point',
    'coordinates': (2.4405558855510354, 41.55034432333448)
})


carles_padros = shape({
    'type': 'Point',
    'coordinates': (2.4414299973605877, 41.54796238394493)
})


parc_central = shape({
    'type': 'Point',
    'coordinates': (2.4418955243451137, 41.544546550658254)
})

pl_geganta = shape({
    'type': 'Point',
    'coordinates': (2.4364283531808453, 41.54133824394662)
})


biada = shape({
    'type': 'Point',
    'coordinates': (2.4269774703756157, 41.539064682961595)
})

cros = shape({
    'type': 'Point',
    'coordinates': (2.420413389954945, 41.53174316433216)
})


points = [maxidecor, mistral, figuera_major, carles_padros, parc_central, pl_geganta, biada, cros]
geo_df_points_2 = gpd.GeoDataFrame(geometry=points, crs=4326)
geo_df_points_2['label'] = ['Maxidecor', 'Mistral', 'Figuera Major', 'Carles Padros', 'Parc Central', 'Pl Gegganta', 'Biada', 'Cros']
geo_df_points_2

                   geometry          label
0  POINT (2.43286 41.55126)      Maxidecor
1  POINT (2.43821 41.54927)        Mistral
2  POINT (2.44056 41.55034)  Figuera Major
3  POINT (2.44143 41.54796)  Carles Padros
4   POINT (2.4419 41.54455)   Parc Central
5  POINT (2.43643 41.54134)    Pl Gegganta
6  POINT (2.42698 41.53906)          Biada
7  POINT (2.42041 41.53174)           Cros

# E11.1

In [101]:
# sortida

tereses = shape({
    'type': 'Point',
    'coordinates': ( 2.442468414555033, 41.53872952476961)
})


isidor = shape({
    'type': 'Point',
    'coordinates': (2.4400547317500036, 41.540915378979896)
})

pl_geganta = shape({
    'type': 'Point',
    'coordinates': (2.4364283531808453, 41.54133824394662)
})

rda_republica = shape({
    'type': 'Point',
    'coordinates': (2.436717607149976, 41.537116032915335)
})

fleming = shape({
    'type': 'Point',
    'coordinates': (2.4397213524233474, 41.53362778761954)
})

laeitana = shape({
    'type': 'Point',
    'coordinates': (2.4361699801650762, 41.53060824479388)
})

points = [tereses, isidor, pl_geganta, rda_republica, fleming, laeitana]
geo_df_points_1 = gpd.GeoDataFrame(geometry=points, crs=4326)
geo_df_points_1['label'] = ['Pl Tereses', 'C Isidor', 'Pl Gegganta', 'Rda Republica', 'Fleming', 'Laeitana']
geo_df_points_1

                   geometry          label
0  POINT (2.44247 41.53873)     Pl Tereses
1  POINT (2.44005 41.54092)       C Isidor
2  POINT (2.43643 41.54134)    Pl Gegganta
3  POINT (2.43672 41.53712)  Rda Republica
4  POINT (2.43972 41.53363)        Fleming
5  POINT (2.43617 41.53061)       Laeitana

# Nomenclator

In [102]:
with open ('data/nomenclator.json') as f:
    nomenclator = json.load(f)
nomenclator_df = pd.DataFrame(nomenclator["equipaments"])
geometry = gpd.GeoSeries.from_wkt(nomenclator_df["WKT"], on_invalid="ignore")

print("Invalid geometries:", geometry.isna().sum())

geodf = gpd.GeoDataFrame(
    nomenclator_df.copy(),
    geometry=geometry,
    crs="EPSG:4326",
)

geodf = geodf.dropna(subset=["geometry"])

Invalid geometries: 63

In [105]:
shape_layer = alt.Chart(geodf).mark_geoshape(size = 0,filled = False,color = 'black')
bus1_layer = alt.Chart(geo_df_points_1).mark_geoshape(size=0, color='red').encode(tooltip=alt.Tooltip('label:N', title='Bus Stop'))
bus2_layer = alt.Chart(geo_df_points_2).mark_geoshape(size=0, color='blue').encode(tooltip=alt.Tooltip('label:N', title='Bus Stop'))
(shape_layer+ bus1_layer+ bus2_layer).properties(
    width=600,
    height=600
)

alt.LayerChart(...)